#!/usr/bin/env python3
"""failure_codes.py — WorldForge v0.9 canonical validation failure codes.

Stable, machine-readable identifiers for *why* a check failed, so reports,
audits, package-check, and the operator runbook can categorize and triage
failures consistently instead of grepping free-text detail strings.

These codes are ADDITIVE: validators still emit a human-readable ``detail`` for
every check; the code is an optional, stable categorization passed alongside.
The free-text ``detail`` remains the source of specifics — the code is the
bucket.

Code shape: ``WFnnn_SHORT_NAME``.  Numbers are grouped by surface:

    000–009  descriptor / parsing
    010–019  registry / ownership
    020–029  provenance
    030–039  generated artifacts (heightmaps, masks, maps, descriptors)
    040–049  path policy (Houdini Temp/Bake, owned-tree, catalog membership)
    050–059  ownership integrity (human templates, destroyable flags)
    060–069  budget
    070–079  runtime state / scenarios
    080–089  UE materialization (tooling drives the editor)
    090–099  packaging

The taxonomy doc (docs/contracts/v0_9_failure_taxonomy.md) is the human-facing
companion: severity, what it means, and how to clear it.
"""


class FailureCode:
    # -- descriptor / parsing (000) -----------------------------------------
    DESCRIPTOR_MISSING = "WF000_DESCRIPTOR_MISSING"
    DESCRIPTOR_UNPARSEABLE = "WF001_DESCRIPTOR_UNPARSEABLE"
    RECIPE_MISSING = "WF002_RECIPE_MISSING"
    SPEC_INVALID = "WF003_SPEC_INVALID"

    # -- registry / ownership (010) -----------------------------------------
    REGISTRY_MISSING_ENTRY = "WF010_REGISTRY_MISSING_ENTRY"
    REGISTRY_INCONSISTENT = "WF011_REGISTRY_INCONSISTENT"
    OWNER_UNRESOLVABLE = "WF012_OWNER_UNRESOLVABLE"

    # -- provenance (020) ----------------------------------------------------
    PROVENANCE_MISSING = "WF020_PROVENANCE_MISSING"
    PROVENANCE_INCOMPLETE = "WF021_PROVENANCE_INCOMPLETE"

    # -- generated artifacts (030) ------------------------------------------
    ARTIFACT_MISSING = "WF030_ARTIFACT_MISSING"
    ARTIFACT_DEGENERATE = "WF031_ARTIFACT_DEGENERATE"
    DIMENSIONS_INVALID = "WF032_DIMENSIONS_INVALID"
    MAP_INVALID = "WF033_MAP_INVALID"

    # -- path policy (040) ---------------------------------------------------
    FORBIDDEN_PATH = "WF040_FORBIDDEN_PATH"
    PATH_NOT_OWNED = "WF041_PATH_NOT_OWNED"
    CATALOG_MEMBERSHIP_MISSING = "WF042_CATALOG_MEMBERSHIP_MISSING"
    TEMP_PATH_AS_FINAL = "WF043_TEMP_PATH_AS_FINAL"

    # -- ownership integrity (050) ------------------------------------------
    HUMAN_TEMPLATE_MARKED_GENERATED = "WF050_HUMAN_TEMPLATE_MARKED_GENERATED"
    GENERATED_FLAG_MISSING = "WF051_GENERATED_FLAG_MISSING"
    DESTROYABLE_HUMAN_OWNED = "WF052_DESTROYABLE_HUMAN_OWNED"

    # -- budget (060) --------------------------------------------------------
    BUDGET_EXCEEDED = "WF060_BUDGET_EXCEEDED"
    BUDGET_PROFILE_MISSING = "WF061_BUDGET_PROFILE_MISSING"

    # -- runtime state / scenarios (070) ------------------------------------
    SCENARIO_UNPARSEABLE = "WF070_SCENARIO_UNPARSEABLE"
    TARGET_MAP_UNRESOLVED = "WF071_TARGET_MAP_UNRESOLVED"
    STATE_DELTA_UNBOUNDED = "WF072_STATE_DELTA_UNBOUNDED"
    MPC_VALUE_MISMATCH = "WF073_MPC_VALUE_MISMATCH"
    POI_EVIDENCE_MISSING = "WF074_POI_EVIDENCE_MISSING"
    SAVE_LOAD_ROUNDTRIP_FAILED = "WF075_SAVE_LOAD_ROUNDTRIP_FAILED"
    STATE_MUTATION_MISMATCH = "WF076_STATE_MUTATION_MISMATCH"
    AGGREGATE_INCONSISTENT = "WF077_AGGREGATE_INCONSISTENT"

    # -- UE materialization (080) — tooling drives the editor to produce these
    UE_ARTIFACT_MISSING = "WF080_UE_ARTIFACT_MISSING"
    UE_ASSET_NOT_STATIC_MESH = "WF081_UE_ASSET_NOT_STATIC_MESH"
    UE_STATE_NOT_APPLIED = "WF082_UE_STATE_NOT_APPLIED"

    # -- packaging / aggregation rollup (090) --------------------------------
    PACKAGE_FORBIDDEN_DEPENDENCY = "WF090_PACKAGE_FORBIDDEN_DEPENDENCY"
    PACKAGE_UNRESOLVED_REFERENCE = "WF091_PACKAGE_UNRESOLVED_REFERENCE"
    PACKAGE_MISSING_OWNED_ASSET = "WF092_PACKAGE_MISSING_OWNED_ASSET"
    CHILD_VALIDATION_FAILED = "WF093_CHILD_VALIDATION_FAILED"

    # ======================================================================
    # v1.0x hardening — gate-level failure taxonomy (100–260)
    # ----------------------------------------------------------------------
    # These are COARSER than the WF0xx codes above: one per full-shield gate
    # class, so the shared failure taxonomy in the v1.0x brief maps 1:1 to a
    # stable code. Fine-grained WF0xx codes still describe the specific defect;
    # a gate code buckets which lane owns it. Every v1.0x validator SHOULD tag
    # its blocking failures with the matching gate code so full-shield can roll
    # failures up by lane.
    # ======================================================================

    # -- report integrity / no-fake-green (100) -----------------------------
    REPORT_INTEGRITY_FAILURE = "WF100_REPORT_INTEGRITY_FAILURE"
    REPORT_MISSING = "WF101_REPORT_MISSING"
    REPORT_EMPTY = "WF102_REPORT_EMPTY"
    REPORT_STALE = "WF103_REPORT_STALE"
    REPORT_ZERO_RECORD = "WF104_REPORT_ZERO_RECORD"
    RECORD_COUNT_MISMATCH = "WF105_RECORD_COUNT_MISMATCH"
    VALIDATOR_SKIPPED = "WF106_VALIDATOR_SKIPPED"
    UNKNOWN_SCHEMA_FIELD = "WF107_UNKNOWN_SCHEMA_FIELD"
    IMPLICIT_FALLBACK_DEFAULT = "WF108_IMPLICIT_FALLBACK_DEFAULT"
    PARTIAL_SUCCESS_AS_SUCCESS = "WF109_PARTIAL_SUCCESS_AS_SUCCESS"

    # -- contract / generation (110) ----------------------------------------
    CONTRACT_FAILURE = "WF110_CONTRACT_FAILURE"
    GENERATION_FAILURE = "WF111_GENERATION_FAILURE"
    ASSET_REFERENCE_FAILURE = "WF112_ASSET_REFERENCE_FAILURE"
    OWNERSHIP_FAILURE = "WF113_OWNERSHIP_FAILURE"

    # -- environment / visual profiles (120) --------------------------------
    ENVIRONMENT_PROFILE_FAILURE = "WF120_ENVIRONMENT_PROFILE_FAILURE"
    VISUAL_STYLE_FAILURE = "WF121_VISUAL_STYLE_FAILURE"
    PROFILE_NOT_MATERIAL = "WF122_PROFILE_NOT_MATERIAL"
    PROFILE_INCOMPATIBLE = "WF123_PROFILE_INCOMPATIBLE"
    PROFILE_MISSING_BINDING = "WF124_PROFILE_MISSING_BINDING"

    # -- sky / lighting / fog / atmosphere (130) ----------------------------
    SKY_PROFILE_FAILURE = "WF130_SKY_PROFILE_FAILURE"
    LIGHTING_PROFILE_FAILURE = "WF131_LIGHTING_PROFILE_FAILURE"
    FOG_PROFILE_FAILURE = "WF132_FOG_PROFILE_FAILURE"
    ATMOSPHERE_PROFILE_FAILURE = "WF133_ATMOSPHERE_PROFILE_FAILURE"
    VISIBILITY_MINIMUM_VIOLATED = "WF134_VISIBILITY_MINIMUM_VIOLATED"
    EXPOSURE_OUT_OF_RANGE = "WF135_EXPOSURE_OUT_OF_RANGE"

    # -- POI / level design / reachability (140) ----------------------------
    POI_USABILITY_FAILURE = "WF140_POI_USABILITY_FAILURE"
    LEVEL_DESIGN_FAILURE = "WF141_LEVEL_DESIGN_FAILURE"
    REACHABILITY_FAILURE = "WF142_REACHABILITY_FAILURE"
    POI_GRAPH_FAILURE = "WF143_POI_GRAPH_FAILURE"
    POI_PLACEMENT_INVALID = "WF144_POI_PLACEMENT_INVALID"

    # -- entity anchors / encounter substrate (150) -------------------------
    ENTITY_ANCHOR_FAILURE = "WF150_ENTITY_ANCHOR_FAILURE"
    NPC_SPAWN_FAILURE = "WF151_NPC_SPAWN_FAILURE"
    ENCOUNTER_READINESS_FAILURE = "WF152_ENCOUNTER_READINESS_FAILURE"
    ENTITY_DENSITY_EXCEEDED = "WF153_ENTITY_DENSITY_EXCEEDED"

    # -- rendering / scalability / ray tracing / budgets (160) --------------
    RENDERING_PROFILE_FAILURE = "WF160_RENDERING_PROFILE_FAILURE"
    SCALABILITY_FAILURE = "WF161_SCALABILITY_FAILURE"
    RAYTRACING_FAILURE = "WF162_RAYTRACING_FAILURE"
    BUDGET_FAILURE = "WF163_BUDGET_FAILURE"
    FRAME_RISK_EXCEEDED = "WF164_FRAME_RISK_EXCEEDED"

    # -- scenario / package (170) -------------------------------------------
    SCENARIO_FAILURE = "WF170_SCENARIO_FAILURE"
    PACKAGE_FAILURE = "WF171_PACKAGE_FAILURE"

    # -- lifecycle / determinism / fuzz / regression (180) ------------------
    LIFECYCLE_FAILURE = "WF180_LIFECYCLE_FAILURE"
    DETERMINISM_FAILURE = "WF181_DETERMINISM_FAILURE"
    REGRESSION_FAILURE = "WF182_REGRESSION_FAILURE"
    FUZZ_FAILURE = "WF183_FUZZ_FAILURE"
    CORRUPTION_UNDETECTED = "WF184_CORRUPTION_UNDETECTED"
    REPAIR_TOUCHED_HUMAN_OWNED = "WF185_REPAIR_TOUCHED_HUMAN_OWNED"

    # ======================================================================
    # v1.1 BiomeForge — multi-environment expansion taxonomy (190–219)
    # ----------------------------------------------------------------------
    # ADDITIVE to the v1.0x taxonomy: one code per BiomeForge gate class so the
    # biome_expansion_world full-shield can roll biome failures up by lane the
    # same way v1.0x rolls up by gate. Fine-grained WF0xx codes still describe
    # the specific defect; these bucket which biome lane owns it. Do NOT reuse
    # or renumber a v1.0x code — extend cleanly here.
    # ======================================================================
    BIOME_CONTRACT_FAILURE = "WF190_BIOME_CONTRACT_FAILURE"
    BIOME_MATRIX_FAILURE = "WF191_BIOME_MATRIX_FAILURE"
    BIOME_PROFILE_BINDING_FAILURE = "WF192_BIOME_PROFILE_BINDING_FAILURE"
    BIOME_ENVIRONMENT_COMPATIBILITY_FAILURE = "WF193_BIOME_ENVIRONMENT_COMPATIBILITY_FAILURE"
    TERRAIN_FORM_FAILURE = "WF194_TERRAIN_FORM_FAILURE"
    MATERIAL_FAMILY_FAILURE = "WF195_MATERIAL_FAMILY_FAILURE"
    VEGETATION_PROFILE_FAILURE = "WF196_VEGETATION_PROFILE_FAILURE"
    PLACEMENT_PROFILE_FAILURE = "WF197_PLACEMENT_PROFILE_FAILURE"
    BIOME_POI_COMPATIBILITY_FAILURE = "WF198_BIOME_POI_COMPATIBILITY_FAILURE"
    BIOME_TRAVERSAL_FAILURE = "WF199_BIOME_TRAVERSAL_FAILURE"
    BIOME_ECOLOGY_FAILURE = "WF200_BIOME_ECOLOGY_FAILURE"
    BIOME_BUDGET_FAILURE = "WF201_BIOME_BUDGET_FAILURE"
    BIOME_PACKAGE_FAILURE = "WF202_BIOME_PACKAGE_FAILURE"
    BIOME_FUZZ_FAILURE = "WF203_BIOME_FUZZ_FAILURE"

    # ======================================================================
    # v1.2 MeshForge Intake — generated mesh asset taxonomy (210–239)
    # ----------------------------------------------------------------------
    # ADDITIVE to the v1.0x / v1.1 taxonomy: one code per MeshForge Intake gate
    # class so the biome_expansion_world full-shield (MESHES=1) can roll mesh
    # failures up by lane. Fine-grained WF0xx codes still describe the specific
    # defect; these bucket which mesh lane owns it. Do NOT reuse or renumber an
    # earlier code — extend cleanly here.
    # ======================================================================
    MESH_CONTRACT_FAILURE = "WF210_MESH_CONTRACT_FAILURE"
    MESH_CATALOG_FAILURE = "WF211_MESH_CATALOG_FAILURE"
    MESH_PROVENANCE_FAILURE = "WF212_MESH_PROVENANCE_FAILURE"
    MESH_OWNERSHIP_FAILURE = "WF213_MESH_OWNERSHIP_FAILURE"
    MESH_FINAL_PATH_FAILURE = "WF214_MESH_FINAL_PATH_FAILURE"
    MESH_SOURCE_FAILURE = "WF215_MESH_SOURCE_FAILURE"
    MESH_MATERIAL_BINDING_FAILURE = "WF216_MESH_MATERIAL_BINDING_FAILURE"
    MESH_COLLISION_FAILURE = "WF217_MESH_COLLISION_FAILURE"
    MESH_BOUNDS_FAILURE = "WF218_MESH_BOUNDS_FAILURE"
    MESH_PIVOT_FAILURE = "WF219_MESH_PIVOT_FAILURE"
    MESH_SCALE_FAILURE = "WF220_MESH_SCALE_FAILURE"
    MESH_PCG_ELIGIBILITY_FAILURE = "WF221_MESH_PCG_ELIGIBILITY_FAILURE"
    MESH_BIOME_COMPATIBILITY_FAILURE = "WF222_MESH_BIOME_COMPATIBILITY_FAILURE"
    MESH_RENDERING_BUDGET_FAILURE = "WF223_MESH_RENDERING_BUDGET_FAILURE"
    MESH_PACKAGE_FAILURE = "WF224_MESH_PACKAGE_FAILURE"
    MESH_LIFECYCLE_FAILURE = "WF225_MESH_LIFECYCLE_FAILURE"
    MESH_REPAIR_FAILURE = "WF226_MESH_REPAIR_FAILURE"
    MESH_DESTROY_FAILURE = "WF227_MESH_DESTROY_FAILURE"
    MESH_NEGATIVE_FIXTURE_FAILURE = "WF228_MESH_NEGATIVE_FIXTURE_FAILURE"

    # ======================================================================
    # v1.2 addendum — Houdini intake taxonomy (230–239)
    # ----------------------------------------------------------------------
    # Houdini is a GENERATED backend: the baked/imported output WorldForge
    # creates is generated_owned, but the source HDA must NOT be assumed
    # generated-owned. These bucket Houdini-intake gate failures by lane.
    # ======================================================================
    HOUDINI_SOURCE_FAILURE = "WF230_HOUDINI_SOURCE_FAILURE"
    HOUDINI_HDA_OWNERSHIP_FAILURE = "WF231_HOUDINI_HDA_OWNERSHIP_FAILURE"
    HOUDINI_PARAMETER_FAILURE = "WF232_HOUDINI_PARAMETER_FAILURE"
    HOUDINI_COOK_FAILURE = "WF233_HOUDINI_COOK_FAILURE"
    HOUDINI_BAKE_FAILURE = "WF234_HOUDINI_BAKE_FAILURE"
    HOUDINI_IMPORT_FAILURE = "WF235_HOUDINI_IMPORT_FAILURE"
    HOUDINI_OUTPUT_REGISTRY_FAILURE = "WF236_HOUDINI_OUTPUT_REGISTRY_FAILURE"
    HOUDINI_OUTPUT_PROVENANCE_FAILURE = "WF237_HOUDINI_OUTPUT_PROVENANCE_FAILURE"
    HOUDINI_OUTPUT_PACKAGE_FAILURE = "WF238_HOUDINI_OUTPUT_PACKAGE_FAILURE"

    # ======================================================================
    # v1.2 addendum — Megascans / external-asset taxonomy (240–255)
    # ----------------------------------------------------------------------
    # Megascans is a THIRD-PARTY external library: third_party_owned, licensed,
    # repair/destroy-protected. The most dangerous bug this taxonomy guards
    # against is lifecycle treating a source cache file like generated output.
    # ======================================================================
    MEGASCANS_LIBRARY_FAILURE = "WF240_MEGASCANS_LIBRARY_FAILURE"
    MEGASCANS_SCAN_FAILURE = "WF241_MEGASCANS_SCAN_FAILURE"
    MEGASCANS_CATALOG_FAILURE = "WF242_MEGASCANS_CATALOG_FAILURE"
    MEGASCANS_BINDING_FAILURE = "WF243_MEGASCANS_BINDING_FAILURE"
    MEGASCANS_PCG_ELIGIBILITY_FAILURE = "WF244_MEGASCANS_PCG_ELIGIBILITY_FAILURE"
    MEGASCANS_BIOME_COMPATIBILITY_FAILURE = "WF245_MEGASCANS_BIOME_COMPATIBILITY_FAILURE"
    EXTERNAL_ASSET_OWNERSHIP_FAILURE = "WF246_EXTERNAL_ASSET_OWNERSHIP_FAILURE"
    EXTERNAL_LICENSE_METADATA_FAILURE = "WF247_EXTERNAL_LICENSE_METADATA_FAILURE"
    THIRD_PARTY_ASSET_DESTROY_RISK = "WF248_THIRD_PARTY_ASSET_DESTROY_RISK"
    THIRD_PARTY_ASSET_PACKAGE_POLICY_FAILURE = "WF249_THIRD_PARTY_ASSET_PACKAGE_POLICY_FAILURE"
    DERIVED_OUTPUT_PROVENANCE_FAILURE = "WF250_DERIVED_OUTPUT_PROVENANCE_FAILURE"
    SOURCE_OWNERSHIP_SEPARATION_FAILURE = "WF251_SOURCE_OWNERSHIP_SEPARATION_FAILURE"

    # ======================================================================
    # v1.3 MissionForge — mission layer taxonomy (260–279)
    # ----------------------------------------------------------------------
    # A mission is biome-aware playable purpose layered over a generated map.
    # These bucket mission-gate failures by lane.
    # ======================================================================
    MISSION_CONTRACT_FAILURE = "WF260_MISSION_CONTRACT_FAILURE"
    MISSION_GRAPH_FAILURE = "WF261_MISSION_GRAPH_FAILURE"
    MISSION_PLACEMENT_FAILURE = "WF262_MISSION_PLACEMENT_FAILURE"
    MISSION_ROUTE_FAILURE = "WF263_MISSION_ROUTE_FAILURE"
    MISSION_OBJECTIVE_FAILURE = "WF264_MISSION_OBJECTIVE_FAILURE"
    MISSION_STATE_FAILURE = "WF265_MISSION_STATE_FAILURE"
    MISSION_SAVE_LOAD_FAILURE = "WF266_MISSION_SAVE_LOAD_FAILURE"
    MISSION_REWARD_FAILURE = "WF267_MISSION_REWARD_FAILURE"
    MISSION_BIOME_COMPATIBILITY_FAILURE = "WF268_MISSION_BIOME_COMPATIBILITY_FAILURE"
    MISSION_MESH_DEPENDENCY_FAILURE = "WF269_MISSION_MESH_DEPENDENCY_FAILURE"

    # ======================================================================
    # v1.3 PlaytestForge — automated playtest taxonomy (280–289)
    # ----------------------------------------------------------------------
    # A generated mission is only real if a playtest harness can complete it.
    # ======================================================================
    PLAYTEST_CONTRACT_FAILURE = "WF280_PLAYTEST_CONTRACT_FAILURE"
    PLAYTEST_ROUTE_FAILURE = "WF281_PLAYTEST_ROUTE_FAILURE"
    PLAYTEST_ACTION_FAILURE = "WF282_PLAYTEST_ACTION_FAILURE"
    PLAYTEST_COMPLETION_FAILURE = "WF283_PLAYTEST_COMPLETION_FAILURE"
    PLAYTEST_STATE_TRANSITION_FAILURE = "WF284_PLAYTEST_STATE_TRANSITION_FAILURE"
    PLAYTEST_SAVE_LOAD_FAILURE = "WF285_PLAYTEST_SAVE_LOAD_FAILURE"
    PLAYTEST_REPORT_FAILURE = "WF286_PLAYTEST_REPORT_FAILURE"

    # ======================================================================
    # v1.3.5 VisualFidelityForge — visual realization taxonomy (290–309)
    # ----------------------------------------------------------------------
    # Materialize biome/mission substrate with surfaces, dressing, atmosphere,
    # and source-safe assets WITHOUT breaking playability/budget/lifecycle.
    # ======================================================================
    VISUAL_ASSET_COVERAGE_FAILURE = "WF290_VISUAL_ASSET_COVERAGE_FAILURE"
    SURFACE_MATERIALIZATION_FAILURE = "WF291_SURFACE_MATERIALIZATION_FAILURE"
    WORLD_DRESSING_FAILURE = "WF292_WORLD_DRESSING_FAILURE"
    ENVIRONMENT_RIG_FAILURE = "WF293_ENVIRONMENT_RIG_FAILURE"
    SKY_MATERIALIZATION_FAILURE = "WF294_SKY_MATERIALIZATION_FAILURE"
    FOG_MATERIALIZATION_FAILURE = "WF295_FOG_MATERIALIZATION_FAILURE"
    CLOUD_MATERIALIZATION_FAILURE = "WF296_CLOUD_MATERIALIZATION_FAILURE"
    LIGHTING_EXPOSURE_FAILURE = "WF297_LIGHTING_EXPOSURE_FAILURE"
    POST_PROCESS_PROFILE_FAILURE = "WF298_POST_PROCESS_PROFILE_FAILURE"
    WEATHER_VFX_FAILURE = "WF299_WEATHER_VFX_FAILURE"
    VISUAL_READABILITY_FAILURE = "WF300_VISUAL_READABILITY_FAILURE"
    VISUAL_BUDGET_FAILURE = "WF301_VISUAL_BUDGET_FAILURE"
    VISUAL_PACKAGE_FAILURE = "WF302_VISUAL_PACKAGE_FAILURE"
    VISUAL_LIFECYCLE_FAILURE = "WF303_VISUAL_LIFECYCLE_FAILURE"

    # ======================================================================
    # v1.4 EncounterForge — encounter pressure taxonomy (310–329)
    # ----------------------------------------------------------------------
    # Generate biome/mission-aware encounter pressure that challenges the
    # mission WITHOUT breaking completion, budgets, state, or lifecycle.
    # ======================================================================
    ENCOUNTER_CONTRACT_FAILURE = "WF310_ENCOUNTER_CONTRACT_FAILURE"
    ENCOUNTER_ARCHETYPE_FAILURE = "WF311_ENCOUNTER_ARCHETYPE_FAILURE"
    ENCOUNTER_SPAWN_GROUP_FAILURE = "WF312_ENCOUNTER_SPAWN_GROUP_FAILURE"
    ENCOUNTER_ANCHOR_FAILURE = "WF313_ENCOUNTER_ANCHOR_FAILURE"
    ENCOUNTER_ROUTE_FAILURE = "WF314_ENCOUNTER_ROUTE_FAILURE"
    ENCOUNTER_PRESSURE_FAILURE = "WF315_ENCOUNTER_PRESSURE_FAILURE"
    ENCOUNTER_PACING_FAILURE = "WF316_ENCOUNTER_PACING_FAILURE"
    ENCOUNTER_BIOME_COMPATIBILITY_FAILURE = "WF317_ENCOUNTER_BIOME_COMPATIBILITY_FAILURE"
    ENCOUNTER_MISSION_COMPATIBILITY_FAILURE = "WF318_ENCOUNTER_MISSION_COMPATIBILITY_FAILURE"
    ENCOUNTER_MESH_DEPENDENCY_FAILURE = "WF319_ENCOUNTER_MESH_DEPENDENCY_FAILURE"
    ENCOUNTER_STATE_FAILURE = "WF320_ENCOUNTER_STATE_FAILURE"
    ENCOUNTER_SAVE_LOAD_FAILURE = "WF321_ENCOUNTER_SAVE_LOAD_FAILURE"
    ENCOUNTER_REWARD_FAILURE = "WF322_ENCOUNTER_REWARD_FAILURE"
    ENCOUNTER_BALANCE_FAILURE = "WF323_ENCOUNTER_BALANCE_FAILURE"
    ENCOUNTER_PACKAGE_FAILURE = "WF324_ENCOUNTER_PACKAGE_FAILURE"
    ENCOUNTER_LIFECYCLE_FAILURE = "WF325_ENCOUNTER_LIFECYCLE_FAILURE"

    # ======================================================================
    # v1.4 PlaytestForge Beta — encounter-aware completion (330–339)
    # ======================================================================
    PLAYTEST_BETA_CONTRACT_FAILURE = "WF330_PLAYTEST_BETA_CONTRACT_FAILURE"
    PLAYTEST_BETA_ROUTE_FAILURE = "WF331_PLAYTEST_BETA_ROUTE_FAILURE"
    PLAYTEST_BETA_ENCOUNTER_RESOLUTION_FAILURE = "WF332_PLAYTEST_BETA_ENCOUNTER_RESOLUTION_FAILURE"
    PLAYTEST_BETA_PRESSURE_FAILURE = "WF333_PLAYTEST_BETA_PRESSURE_FAILURE"
    PLAYTEST_BETA_COMPLETION_FAILURE = "WF334_PLAYTEST_BETA_COMPLETION_FAILURE"
    PLAYTEST_BETA_SAVE_LOAD_FAILURE = "WF335_PLAYTEST_BETA_SAVE_LOAD_FAILURE"
    PLAYTEST_BETA_REPORT_FAILURE = "WF336_PLAYTEST_BETA_REPORT_FAILURE"

    # ======================================================================
    # v1.4 BalanceForge Alpha — classification guardrails (340–349)
    # ======================================================================
    BALANCE_CONTRACT_FAILURE = "WF340_BALANCE_CONTRACT_FAILURE"
    BALANCE_REPORT_FAILURE = "WF341_BALANCE_REPORT_FAILURE"

    # ======================================================================
    # v1.5 AssetAcquisitionForge — safe acquisition taxonomy (350–376)
    # ----------------------------------------------------------------------
    # Convert content gaps into approved, licensed, provenance-proven,
    # quarantined asset inventory. The most dangerous bugs this guards against:
    # importing paid/EULA-gated content without manual action, accepting unclear
    # licenses, bypassing quarantine, and mismarking third-party as generated.
    # ======================================================================
    ASSET_NEED_ANALYSIS_FAILURE = "WF350_ASSET_NEED_ANALYSIS_FAILURE"
    ASSET_PROCUREMENT_MANIFEST_FAILURE = "WF351_ASSET_PROCUREMENT_MANIFEST_FAILURE"
    ASSET_SOURCE_POLICY_FAILURE = "WF352_ASSET_SOURCE_POLICY_FAILURE"
    ASSET_SOURCE_ADAPTER_FAILURE = "WF353_ASSET_SOURCE_ADAPTER_FAILURE"
    ASSET_DOWNLOAD_NOT_ALLOWED = "WF354_ASSET_DOWNLOAD_NOT_ALLOWED"
    ASSET_LICENSE_MISSING = "WF355_ASSET_LICENSE_MISSING"
    ASSET_LICENSE_UNSUPPORTED = "WF356_ASSET_LICENSE_UNSUPPORTED"
    ASSET_EULA_REQUIRED_MANUAL_ACTION = "WF357_ASSET_EULA_REQUIRED_MANUAL_ACTION"
    ASSET_PURCHASE_REQUIRED_MANUAL_ACTION = "WF358_ASSET_PURCHASE_REQUIRED_MANUAL_ACTION"
    ASSET_MANUAL_APPROVAL_MISSING = "WF359_ASSET_MANUAL_APPROVAL_MISSING"
    ASSET_PROVENANCE_MISSING = "WF360_ASSET_PROVENANCE_MISSING"
    ASSET_SOURCE_URL_MISSING = "WF361_ASSET_SOURCE_URL_MISSING"
    ASSET_SOURCE_PATH_MISSING = "WF362_ASSET_SOURCE_PATH_MISSING"
    ASSET_HASH_MISSING = "WF363_ASSET_HASH_MISSING"
    ASSET_HASH_MISMATCH = "WF364_ASSET_HASH_MISMATCH"
    ASSET_QUARANTINE_BYPASS = "WF365_ASSET_QUARANTINE_BYPASS"
    ASSET_QUARANTINE_FAILURE = "WF366_ASSET_QUARANTINE_FAILURE"
    ASSET_CATALOG_FAILURE = "WF367_ASSET_CATALOG_FAILURE"
    ASSET_OWNERSHIP_FAILURE = "WF368_ASSET_OWNERSHIP_FAILURE"
    ASSET_PACKAGE_POLICY_FAILURE = "WF369_ASSET_PACKAGE_POLICY_FAILURE"
    ASSET_DEPENDENCY_FAILURE = "WF370_ASSET_DEPENDENCY_FAILURE"
    ASSET_OUTSIDE_APPROVED_ROOT = "WF371_ASSET_OUTSIDE_APPROVED_ROOT"
    ASSET_UNKNOWN_LICENSE_REJECTED = "WF372_ASSET_UNKNOWN_LICENSE_REJECTED"
    ASSET_STANDALONE_REDISTRIBUTION_FORBIDDEN = "WF373_ASSET_STANDALONE_REDISTRIBUTION_FORBIDDEN"
    ASSET_NEED_SCHEMA_FAILURE = "WF374_ASSET_NEED_SCHEMA_FAILURE"
    ASSET_APPROVAL_STATE_FAILURE = "WF375_ASSET_APPROVAL_STATE_FAILURE"
    ASSET_SHOPPING_LIST_FAILURE = "WF376_ASSET_SHOPPING_LIST_FAILURE"
    ASSET_NEGATIVE_FIXTURE_FAILURE = "WF377_ASSET_NEGATIVE_FIXTURE_FAILURE"

    # ======================================================================
    # v1.5 AssetRealizationForge — UE realization + cover replacement (380–398)
    # ----------------------------------------------------------------------
    # Turn approved catalog records into UE-realized assets and replace v1.4x
    # cube cover proxies with real catalog-backed meshes WITHOUT moving anchors,
    # blocking routes, or breaking cover semantics. Hybrid rule: every cover
    # family must have a generated_owned baseline (COVER_BASELINE_MISSING).
    # ======================================================================
    ASSET_UE_MATERIALIZATION_FAILURE = "WF380_ASSET_UE_MATERIALIZATION_FAILURE"
    ASSET_UE_IMPORT_FAILURE = "WF381_ASSET_UE_IMPORT_FAILURE"
    ASSET_UE_PATH_INVALID = "WF382_ASSET_UE_PATH_INVALID"
    ASSET_MATERIAL_BINDING_FAILURE = "WF383_ASSET_MATERIAL_BINDING_FAILURE"
    ASSET_TEXTURE_DEPENDENCY_FAILURE = "WF384_ASSET_TEXTURE_DEPENDENCY_FAILURE"
    ASSET_COLLISION_MISSING = "WF385_ASSET_COLLISION_MISSING"
    ASSET_BOUNDS_INVALID = "WF386_ASSET_BOUNDS_INVALID"
    ASSET_LOD_POLICY_FAILURE = "WF387_ASSET_LOD_POLICY_FAILURE"
    ASSET_NANITE_POLICY_FAILURE = "WF388_ASSET_NANITE_POLICY_FAILURE"
    ASSET_MAP_REFERENCE_FAILURE = "WF389_ASSET_MAP_REFERENCE_FAILURE"
    COVER_PROXY_REPLACEMENT_FAILURE = "WF390_COVER_PROXY_REPLACEMENT_FAILURE"
    COVER_REPLACEMENT_NOT_CATALOG_BACKED = "WF391_COVER_REPLACEMENT_NOT_CATALOG_BACKED"
    COVER_REPLACEMENT_ROUTE_BLOCKED = "WF392_COVER_REPLACEMENT_ROUTE_BLOCKED"
    COVER_REPLACEMENT_COLLISION_INVALID = "WF393_COVER_REPLACEMENT_COLLISION_INVALID"
    COVER_REPLACEMENT_HEIGHT_CLASS_MISMATCH = "WF394_COVER_REPLACEMENT_HEIGHT_CLASS_MISMATCH"
    COVER_REPLACEMENT_LOS_FAILURE = "WF395_COVER_REPLACEMENT_LOS_FAILURE"
    COVER_REPLACEMENT_ANCHOR_MUTATED = "WF396_COVER_REPLACEMENT_ANCHOR_MUTATED"
    COVER_BASELINE_MISSING = "WF397_COVER_BASELINE_MISSING"
    REALIZED_COVER_BINDING_FAILURE = "WF398_REALIZED_COVER_BINDING_FAILURE"

    # ======================================================================
    # v1.5 VisualEnvironmentForge — biome visual kits (400–416)
    # ----------------------------------------------------------------------
    # Give every biome/mission/encounter context a validated visual environment
    # kit and materialize it WITHOUT breaking routes, budgets, ownership, or
    # package policy. Distinct from the v1.3.5 rig codes (290–303): these are
    # kit-composition + per-zone readability codes.
    # ======================================================================
    VISUAL_KIT_CONTRACT_FAILURE = "WF400_VISUAL_KIT_CONTRACT_FAILURE"
    VISUAL_KIT_MISSING_BIOME = "WF401_VISUAL_KIT_MISSING_BIOME"
    VISUAL_SKY_PROFILE_FAILURE = "WF402_VISUAL_SKY_PROFILE_FAILURE"
    VISUAL_FOG_PROFILE_FAILURE = "WF403_VISUAL_FOG_PROFILE_FAILURE"
    VISUAL_LIGHTING_PROFILE_FAILURE = "WF404_VISUAL_LIGHTING_PROFILE_FAILURE"
    VISUAL_ATMOSPHERE_PROFILE_FAILURE = "WF405_VISUAL_ATMOSPHERE_PROFILE_FAILURE"
    VISUAL_POSTPROCESS_PROFILE_FAILURE = "WF406_VISUAL_POSTPROCESS_PROFILE_FAILURE"
    VISUAL_DRESSING_COVERAGE_FAILURE = "WF407_VISUAL_DRESSING_COVERAGE_FAILURE"
    VISUAL_DENSITY_BUDGET_FAILURE = "WF408_VISUAL_DENSITY_BUDGET_FAILURE"
    VISUAL_ROUTE_READABILITY_FAILURE = "WF409_VISUAL_ROUTE_READABILITY_FAILURE"
    VISUAL_HAZARD_READABILITY_FAILURE = "WF410_VISUAL_HAZARD_READABILITY_FAILURE"
    VISUAL_SAFE_ZONE_READABILITY_FAILURE = "WF411_VISUAL_SAFE_ZONE_READABILITY_FAILURE"
    VISUAL_DANGER_ZONE_READABILITY_FAILURE = "WF412_VISUAL_DANGER_ZONE_READABILITY_FAILURE"
    VISUAL_SCREENSHOT_REPORT_FAILURE = "WF413_VISUAL_SCREENSHOT_REPORT_FAILURE"
    VISUAL_KIT_MATERIALIZATION_FAILURE = "WF414_VISUAL_KIT_MATERIALIZATION_FAILURE"
    VISUAL_WEATHER_BINDING_FAILURE = "WF415_VISUAL_WEATHER_BINDING_FAILURE"
    VISUAL_KIT_NEGATIVE_FIXTURE_FAILURE = "WF416_VISUAL_KIT_NEGATIVE_FIXTURE_FAILURE"

    # ======================================================================
    # v1.5 lifecycle / package protection (420–425)
    # ----------------------------------------------------------------------
    # Lifecycle torture must prove third-party / human-owned source assets are
    # never destroyed or mutated, and packaging must never redistribute raw
    # third-party content or leak absolute/cache paths.
    # ======================================================================
    LIFECYCLE_THIRD_PARTY_DESTROY_ATTEMPT = "WF420_LIFECYCLE_THIRD_PARTY_DESTROY_ATTEMPT"
    LIFECYCLE_HUMAN_OWNED_MUTATION_ATTEMPT = "WF421_LIFECYCLE_HUMAN_OWNED_MUTATION_ATTEMPT"
    PACKAGE_EXTERNAL_LICENSE_FAILURE = "WF422_PACKAGE_EXTERNAL_LICENSE_FAILURE"
    PACKAGE_RAW_ASSET_REDISTRIBUTION_FAILURE = "WF423_PACKAGE_RAW_ASSET_REDISTRIBUTION_FAILURE"
    PACKAGE_DEPENDENCY_LEAK_FAILURE = "WF424_PACKAGE_DEPENDENCY_LEAK_FAILURE"
    PACKAGE_ABSOLUTE_PATH_LEAK_FAILURE = "WF425_PACKAGE_ABSOLUTE_PATH_LEAK_FAILURE"

    # ======================================================================
    # v1.5 schema / taxonomy / integrity (430–436)
    # ======================================================================
    V1_5_TAXONOMY_FAILURE = "WF430_V1_5_TAXONOMY_FAILURE"
    VISUAL_KIT_SCHEMA_FAILURE = "WF431_VISUAL_KIT_SCHEMA_FAILURE"
    COVER_BINDING_SCHEMA_FAILURE = "WF432_COVER_BINDING_SCHEMA_FAILURE"
    ASSET_CANDIDATE_SCHEMA_FAILURE = "WF433_ASSET_CANDIDATE_SCHEMA_FAILURE"
    ASSET_QUARANTINE_SCHEMA_FAILURE = "WF434_ASSET_QUARANTINE_SCHEMA_FAILURE"
    V1_5_FUZZ_FAILURE = "WF435_V1_5_FUZZ_FAILURE"
    V1_5_REPORT_INTEGRITY_FAILURE = "WF436_V1_5_REPORT_INTEGRITY_FAILURE"

    # ======================================================================
    # v1.6 LiveRuntimeForge Alpha — runtime execution taxonomy (440–465)
    # ----------------------------------------------------------------------
    # v1.6 is the first RUNTIME-TRUTH milestone: a controlled UE pawn must
    # spawn, be possessed, traverse real navmesh/collision to objective
    # actors, and never fake completion via teleport or graph-only claims.
    # These bucket runtime-execution failures by lane. Fine-grained WF0xx
    # codes still describe the specific defect. Do NOT reuse/renumber an
    # earlier band — extend cleanly here.
    #
    # STAGING NOTE: RUNTIME_LIVE_RUN_PENDING is the one honest exception to
    # "every failure is blocking" — it marks a live-UE gate that cannot run
    # because the editor/NeoStack bridge is offline. It is emitted as a WARN
    # (blocking under STRICT so the shield is never falsely green, non-
    # blocking otherwise so the authoring substrate can be proven), and is
    # explicitly NOT a fake-green path: it never counts as completion.
    # ======================================================================
    RUNTIME_SCENARIO_SCHEMA_FAILURE = "WF440_RUNTIME_SCENARIO_SCHEMA_FAILURE"
    RUNTIME_SCENARIO_GENERATION_FAILURE = "WF441_RUNTIME_SCENARIO_GENERATION_FAILURE"
    RUNTIME_MAP_LOAD_FAILURE = "WF442_RUNTIME_MAP_LOAD_FAILURE"
    RUNTIME_PAWN_PROFILE_FAILURE = "WF443_RUNTIME_PAWN_PROFILE_FAILURE"
    RUNTIME_PAWN_SPAWN_FAILURE = "WF444_RUNTIME_PAWN_SPAWN_FAILURE"
    RUNTIME_PAWN_POSSESSION_FAILURE = "WF445_RUNTIME_PAWN_POSSESSION_FAILURE"
    RUNTIME_NAVMESH_MISSING = "WF446_RUNTIME_NAVMESH_MISSING"
    RUNTIME_NAVMESH_INVALID = "WF447_RUNTIME_NAVMESH_INVALID"
    RUNTIME_ROUTE_PLAN_FAILURE = "WF448_RUNTIME_ROUTE_PLAN_FAILURE"
    RUNTIME_ROUTE_BLOCKED = "WF449_RUNTIME_ROUTE_BLOCKED"
    RUNTIME_ROUTE_TIMEOUT = "WF450_RUNTIME_ROUTE_TIMEOUT"
    RUNTIME_COLLISION_BLOCKED = "WF451_RUNTIME_COLLISION_BLOCKED"
    RUNTIME_COLLISION_INVALID = "WF452_RUNTIME_COLLISION_INVALID"
    RUNTIME_WAYPOINT_UNREACHABLE = "WF453_RUNTIME_WAYPOINT_UNREACHABLE"
    RUNTIME_OBJECTIVE_UNREACHABLE = "WF454_RUNTIME_OBJECTIVE_UNREACHABLE"
    RUNTIME_DRIVER_FAILURE = "WF455_RUNTIME_DRIVER_FAILURE"
    RUNTIME_UE_ERROR_SWALLOWED = "WF456_RUNTIME_UE_ERROR_SWALLOWED"
    RUNTIME_EVIDENCE_FAILURE = "WF457_RUNTIME_EVIDENCE_FAILURE"
    RUNTIME_TELEMETRY_MISSING = "WF458_RUNTIME_TELEMETRY_MISSING"
    RUNTIME_TELEMETRY_INVALID = "WF459_RUNTIME_TELEMETRY_INVALID"
    RUNTIME_PAWN_SCHEMA_FAILURE = "WF460_RUNTIME_PAWN_SCHEMA_FAILURE"
    RUNTIME_ROUTE_PLAN_SCHEMA_FAILURE = "WF461_RUNTIME_ROUTE_PLAN_SCHEMA_FAILURE"
    RUNTIME_TELEMETRY_SCHEMA_FAILURE = "WF462_RUNTIME_TELEMETRY_SCHEMA_FAILURE"
    RUNTIME_COMPLETION_SCHEMA_FAILURE = "WF463_RUNTIME_COMPLETION_SCHEMA_FAILURE"
    RUNTIME_SCENARIO_COVERAGE_FAILURE = "WF464_RUNTIME_SCENARIO_COVERAGE_FAILURE"
    RUNTIME_LIVE_RUN_PENDING = "WF465_RUNTIME_LIVE_RUN_PENDING"

    # ======================================================================
    # v1.6 InteractionForge Alpha — runtime objective actors (470–485)
    # ----------------------------------------------------------------------
    # Materialize generated runtime objective actors for the six mission
    # archetypes; each verb must emit an event and mutate mission state, and
    # completion must persist through save/load.
    # ======================================================================
    INTERACTION_ACTOR_SCHEMA_FAILURE = "WF470_INTERACTION_ACTOR_SCHEMA_FAILURE"
    INTERACTION_ACTOR_MATERIALIZATION_FAILURE = "WF471_INTERACTION_ACTOR_MATERIALIZATION_FAILURE"
    INTERACTION_ACTOR_MISSING = "WF472_INTERACTION_ACTOR_MISSING"
    INTERACTION_ACTOR_DUPLICATE = "WF473_INTERACTION_ACTOR_DUPLICATE"
    INTERACTION_RADIUS_INVALID = "WF474_INTERACTION_RADIUS_INVALID"
    INTERACTION_VERB_UNSUPPORTED = "WF475_INTERACTION_VERB_UNSUPPORTED"
    INTERACTION_LINE_OF_SIGHT_FAILURE = "WF476_INTERACTION_LINE_OF_SIGHT_FAILURE"
    INTERACTION_PROMPT_METADATA_FAILURE = "WF477_INTERACTION_PROMPT_METADATA_FAILURE"
    INTERACTION_EVENT_MISSING = "WF478_INTERACTION_EVENT_MISSING"
    INTERACTION_EVENT_INVALID = "WF479_INTERACTION_EVENT_INVALID"
    INTERACTION_STATE_KEY_MISSING = "WF480_INTERACTION_STATE_KEY_MISSING"
    INTERACTION_STATE_MUTATION_FAILURE = "WF481_INTERACTION_STATE_MUTATION_FAILURE"
    INTERACTION_COMPLETION_CONTRIBUTION_FAILURE = "WF482_INTERACTION_COMPLETION_CONTRIBUTION_FAILURE"
    INTERACTION_SAVE_LOAD_BINDING_FAILURE = "WF483_INTERACTION_SAVE_LOAD_BINDING_FAILURE"
    INTERACTION_MISSION_BRIDGE_FAILURE = "WF484_INTERACTION_MISSION_BRIDGE_FAILURE"
    INTERACTION_NEGATIVE_FIXTURE_FAILURE = "WF485_INTERACTION_NEGATIVE_FIXTURE_FAILURE"

    # ======================================================================
    # v1.6 PlaytestForge Gamma — runtime completion classification (486–495)
    # ----------------------------------------------------------------------
    # Consumes runtime scenarios, classifies actual runtime completion, and
    # rejects every fake-green path (graph-only, teleport, no-telemetry,
    # unchanged-state, skipped save/load, partial/empty/stale report).
    # ======================================================================
    PLAYTEST_GAMMA_SCENARIO_FAILURE = "WF486_PLAYTEST_GAMMA_SCENARIO_FAILURE"
    PLAYTEST_GAMMA_COMPLETION_FAILURE = "WF487_PLAYTEST_GAMMA_COMPLETION_FAILURE"
    PLAYTEST_GAMMA_FALSE_SUCCESS = "WF488_PLAYTEST_GAMMA_FALSE_SUCCESS"
    PLAYTEST_GAMMA_TELEPORT_SUCCESS_FORBIDDEN = "WF489_PLAYTEST_GAMMA_TELEPORT_SUCCESS_FORBIDDEN"
    PLAYTEST_GAMMA_PARTIAL_COMPLETION = "WF490_PLAYTEST_GAMMA_PARTIAL_COMPLETION"
    PLAYTEST_GAMMA_TIMEOUT = "WF491_PLAYTEST_GAMMA_TIMEOUT"
    PLAYTEST_GAMMA_REPORT_FAILURE = "WF492_PLAYTEST_GAMMA_REPORT_FAILURE"
    PLAYTEST_GAMMA_ROLLUP_FAILURE = "WF493_PLAYTEST_GAMMA_ROLLUP_FAILURE"
    PLAYTEST_GAMMA_CONTRACT_FAILURE = "WF494_PLAYTEST_GAMMA_CONTRACT_FAILURE"
    PLAYTEST_GAMMA_STATE_BRIDGE_FAILURE = "WF495_PLAYTEST_GAMMA_STATE_BRIDGE_FAILURE"

    # ======================================================================
    # v1.6 runtime save/load persistence (496–503)
    # ======================================================================
    RUNTIME_SAVE_FAILURE = "WF496_RUNTIME_SAVE_FAILURE"
    RUNTIME_LOAD_FAILURE = "WF497_RUNTIME_LOAD_FAILURE"
    RUNTIME_SAVE_FILE_MISSING = "WF498_RUNTIME_SAVE_FILE_MISSING"
    RUNTIME_SAVE_STATE_MISSING = "WF499_RUNTIME_SAVE_STATE_MISSING"
    RUNTIME_POST_LOAD_STATE_MISMATCH = "WF500_RUNTIME_POST_LOAD_STATE_MISMATCH"
    RUNTIME_COMPLETION_NOT_PERSISTED = "WF501_RUNTIME_COMPLETION_NOT_PERSISTED"
    RUNTIME_SAVE_LOAD_SCHEMA_FAILURE = "WF502_RUNTIME_SAVE_LOAD_SCHEMA_FAILURE"
    RUNTIME_SAVE_LOAD_PROOF_FAILURE = "WF503_RUNTIME_SAVE_LOAD_PROOF_FAILURE"

    # ======================================================================
    # v1.6 runtime report integrity + torture/fuzz/lifecycle/taxonomy (504–515)
    # ======================================================================
    RUNTIME_REPORT_EMPTY = "WF504_RUNTIME_REPORT_EMPTY"
    RUNTIME_REPORT_STALE = "WF505_RUNTIME_REPORT_STALE"
    RUNTIME_REPORT_PARTIAL_SUCCESS = "WF506_RUNTIME_REPORT_PARTIAL_SUCCESS"
    RUNTIME_REPORT_ZERO_RECORD_SUCCESS = "WF507_RUNTIME_REPORT_ZERO_RECORD_SUCCESS"
    RUNTIME_REPORT_MISSING_TELEMETRY = "WF508_RUNTIME_REPORT_MISSING_TELEMETRY"
    RUNTIME_REPORT_MISSING_EVIDENCE = "WF509_RUNTIME_REPORT_MISSING_EVIDENCE"
    RUNTIME_REPORT_INTEGRITY_FAILURE = "WF510_RUNTIME_REPORT_INTEGRITY_FAILURE"
    RUNTIME_LIFECYCLE_FAILURE = "WF511_RUNTIME_LIFECYCLE_FAILURE"
    RUNTIME_NEGATIVE_FIXTURE_FAILURE = "WF512_RUNTIME_NEGATIVE_FIXTURE_FAILURE"
    V1_6_TAXONOMY_FAILURE = "WF513_V1_6_TAXONOMY_FAILURE"
    V1_6_FUZZ_FAILURE = "WF514_V1_6_FUZZ_FAILURE"
    V1_6_REPORT_INTEGRITY_FAILURE = "WF515_V1_6_REPORT_INTEGRITY_FAILURE"

    # --- v1.6y GroundTraversalForge / NavRuntimeForge / route graph (WF516+) ---
    # GroundTraversalForge
    GROUND_TRAVERSAL_SCHEMA_FAILURE = "WF516_GROUND_TRAVERSAL_SCHEMA_FAILURE"
    GROUND_SCENARIO_GENERATION_FAILURE = "WF517_GROUND_SCENARIO_GENERATION_FAILURE"
    GROUND_PAWN_PROFILE_FAILURE = "WF518_GROUND_PAWN_PROFILE_FAILURE"
    GROUND_PAWN_SPAWN_FAILURE = "WF519_GROUND_PAWN_SPAWN_FAILURE"
    GROUND_PAWN_POSSESSION_FAILURE = "WF520_GROUND_PAWN_POSSESSION_FAILURE"
    GROUND_MODE_SELECTION_FAILURE = "WF521_GROUND_MODE_SELECTION_FAILURE"
    GROUND_TRAVERSAL_MODE_FORBIDDEN = "WF522_GROUND_TRAVERSAL_MODE_FORBIDDEN"
    GROUND_FLIGHT_COUNTED_AS_SUCCESS = "WF523_GROUND_FLIGHT_COUNTED_AS_SUCCESS"
    GROUND_TELEPORT_COUNTED_AS_SUCCESS = "WF524_GROUND_TELEPORT_COUNTED_AS_SUCCESS"
    GROUND_ROUTE_TIMEOUT = "WF525_GROUND_ROUTE_TIMEOUT"
    GROUND_OBJECTIVE_APPROACH_BLOCKED = "WF526_GROUND_OBJECTIVE_APPROACH_BLOCKED"
    GROUND_INTERACTION_UNREACHABLE = "WF527_GROUND_INTERACTION_UNREACHABLE"
    GROUND_COMPLETION_FAILURE = "WF528_GROUND_COMPLETION_FAILURE"
    # Walkability
    GROUND_WALKABILITY_ANALYSIS_FAILURE = "WF529_GROUND_WALKABILITY_ANALYSIS_FAILURE"
    GROUND_SURFACE_NOT_WALKABLE = "WF530_GROUND_SURFACE_NOT_WALKABLE"
    GROUND_SLOPE_LIMIT_EXCEEDED = "WF531_GROUND_SLOPE_LIMIT_EXCEEDED"
    GROUND_STEP_HEIGHT_EXCEEDED = "WF532_GROUND_STEP_HEIGHT_EXCEEDED"
    GROUND_CAPSULE_CLEARANCE_FAILURE = "WF533_GROUND_CAPSULE_CLEARANCE_FAILURE"
    GROUND_ROUTE_WIDTH_FAILURE = "WF534_GROUND_ROUTE_WIDTH_FAILURE"
    GROUND_COVER_BLOCKS_ROUTE = "WF535_GROUND_COVER_BLOCKS_ROUTE"
    GROUND_HAZARD_BLOCKS_ROUTE = "WF536_GROUND_HAZARD_BLOCKS_ROUTE"
    GROUND_SAFE_ZONE_UNREACHABLE = "WF537_GROUND_SAFE_ZONE_UNREACHABLE"
    GROUND_DANGER_ZONE_INVALID = "WF538_GROUND_DANGER_ZONE_INVALID"
    GROUND_OBJECTIVE_ACCESS_FAILURE = "WF539_GROUND_OBJECTIVE_ACCESS_FAILURE"
    # NavRuntimeForge
    GROUND_NAVMESH_PROBE_FAILURE = "WF540_GROUND_NAVMESH_PROBE_FAILURE"
    GROUND_NAVMESH_BUILD_FAILURE = "WF541_GROUND_NAVMESH_BUILD_FAILURE"
    GROUND_NAVMESH_MISSING = "WF542_GROUND_NAVMESH_MISSING"
    GROUND_NAVMESH_BOUNDS_MISSING = "WF543_GROUND_NAVMESH_BOUNDS_MISSING"
    GROUND_NAVMESH_INSUFFICIENT_COVERAGE = "WF544_GROUND_NAVMESH_INSUFFICIENT_COVERAGE"
    GROUND_NAVMESH_SPAWN_OFF_NAV = "WF545_GROUND_NAVMESH_SPAWN_OFF_NAV"
    GROUND_NAVMESH_OBJECTIVE_OFF_NAV = "WF546_GROUND_NAVMESH_OBJECTIVE_OFF_NAV"
    GROUND_NAVMESH_PATH_MISSING = "WF547_GROUND_NAVMESH_PATH_MISSING"
    GROUND_NAVMESH_RUNTIME_UNAVAILABLE = "WF548_GROUND_NAVMESH_RUNTIME_UNAVAILABLE"
    # Route graph
    GROUND_ROUTE_GRAPH_FAILURE = "WF549_GROUND_ROUTE_GRAPH_FAILURE"
    GROUND_ROUTE_GRAPH_MISSING = "WF550_GROUND_ROUTE_GRAPH_MISSING"
    GROUND_ROUTE_NODE_INVALID = "WF551_GROUND_ROUTE_NODE_INVALID"
    GROUND_ROUTE_EDGE_INVALID = "WF552_GROUND_ROUTE_EDGE_INVALID"
    GROUND_ROUTE_UNREACHABLE = "WF553_GROUND_ROUTE_UNREACHABLE"
    GROUND_ROUTE_COLLISION_FAILURE = "WF554_GROUND_ROUTE_COLLISION_FAILURE"
    GROUND_ROUTE_COVER_INTRUSION = "WF555_GROUND_ROUTE_COVER_INTRUSION"
    GROUND_ROUTE_HAZARD_INTRUSION = "WF556_GROUND_ROUTE_HAZARD_INTRUSION"
    GROUND_ROUTE_OBJECTIVE_APPROACH_FAILURE = "WF557_GROUND_ROUTE_OBJECTIVE_APPROACH_FAILURE"
    # Reports
    GROUND_REPORT_MISSING_MODE = "WF558_GROUND_REPORT_MISSING_MODE"
    GROUND_REPORT_MISSING_TELEMETRY = "WF559_GROUND_REPORT_MISSING_TELEMETRY"
    GROUND_REPORT_STALE = "WF560_GROUND_REPORT_STALE"
    GROUND_REPORT_ZERO_RECORD_SUCCESS = "WF561_GROUND_REPORT_ZERO_RECORD_SUCCESS"
    GROUND_REPORT_PARTIAL_MATRIX = "WF562_GROUND_REPORT_PARTIAL_MATRIX"
    GROUND_REPORT_INTEGRITY_FAILURE = "WF563_GROUND_REPORT_INTEGRITY_FAILURE"


# severity hint per code: "fail" (blocking) or "warn" (soft / strict-blocking).
# This is the *default* nature of the code; a validator may still choose a
# stricter verdict for context.
SEVERITY = {
    FailureCode.DESCRIPTOR_MISSING: "fail",
    FailureCode.DESCRIPTOR_UNPARSEABLE: "fail",
    FailureCode.RECIPE_MISSING: "fail",
    FailureCode.SPEC_INVALID: "fail",
    FailureCode.REGISTRY_MISSING_ENTRY: "fail",
    FailureCode.REGISTRY_INCONSISTENT: "fail",
    FailureCode.OWNER_UNRESOLVABLE: "fail",
    FailureCode.PROVENANCE_MISSING: "fail",
    FailureCode.PROVENANCE_INCOMPLETE: "fail",
    FailureCode.ARTIFACT_MISSING: "fail",
    FailureCode.ARTIFACT_DEGENERATE: "fail",
    FailureCode.DIMENSIONS_INVALID: "fail",
    FailureCode.MAP_INVALID: "fail",
    FailureCode.FORBIDDEN_PATH: "fail",
    FailureCode.PATH_NOT_OWNED: "fail",
    FailureCode.CATALOG_MEMBERSHIP_MISSING: "fail",
    FailureCode.TEMP_PATH_AS_FINAL: "fail",
    FailureCode.HUMAN_TEMPLATE_MARKED_GENERATED: "fail",
    FailureCode.GENERATED_FLAG_MISSING: "fail",
    FailureCode.DESTROYABLE_HUMAN_OWNED: "fail",
    FailureCode.BUDGET_EXCEEDED: "fail",
    FailureCode.BUDGET_PROFILE_MISSING: "warn",
    FailureCode.SCENARIO_UNPARSEABLE: "fail",
    FailureCode.TARGET_MAP_UNRESOLVED: "fail",
    FailureCode.STATE_DELTA_UNBOUNDED: "fail",
    FailureCode.MPC_VALUE_MISMATCH: "fail",
    FailureCode.POI_EVIDENCE_MISSING: "fail",
    FailureCode.SAVE_LOAD_ROUNDTRIP_FAILED: "fail",
    FailureCode.STATE_MUTATION_MISMATCH: "fail",
    FailureCode.AGGREGATE_INCONSISTENT: "fail",
    FailureCode.UE_ARTIFACT_MISSING: "fail",
    FailureCode.UE_ASSET_NOT_STATIC_MESH: "fail",
    FailureCode.UE_STATE_NOT_APPLIED: "fail",
    FailureCode.PACKAGE_FORBIDDEN_DEPENDENCY: "fail",
    FailureCode.PACKAGE_UNRESOLVED_REFERENCE: "fail",
    FailureCode.PACKAGE_MISSING_OWNED_ASSET: "fail",
    FailureCode.CHILD_VALIDATION_FAILED: "fail",
    # v1.0x gate-level codes — every gate failure is blocking by nature.
    FailureCode.REPORT_INTEGRITY_FAILURE: "fail",
    FailureCode.REPORT_MISSING: "fail",
    FailureCode.REPORT_EMPTY: "fail",
    FailureCode.REPORT_STALE: "fail",
    FailureCode.REPORT_ZERO_RECORD: "fail",
    FailureCode.RECORD_COUNT_MISMATCH: "fail",
    FailureCode.VALIDATOR_SKIPPED: "fail",
    FailureCode.UNKNOWN_SCHEMA_FIELD: "fail",
    FailureCode.IMPLICIT_FALLBACK_DEFAULT: "fail",
    FailureCode.PARTIAL_SUCCESS_AS_SUCCESS: "fail",
    FailureCode.CONTRACT_FAILURE: "fail",
    FailureCode.GENERATION_FAILURE: "fail",
    FailureCode.ASSET_REFERENCE_FAILURE: "fail",
    FailureCode.OWNERSHIP_FAILURE: "fail",
    FailureCode.ENVIRONMENT_PROFILE_FAILURE: "fail",
    FailureCode.VISUAL_STYLE_FAILURE: "fail",
    FailureCode.PROFILE_NOT_MATERIAL: "fail",
    FailureCode.PROFILE_INCOMPATIBLE: "fail",
    FailureCode.PROFILE_MISSING_BINDING: "fail",
    FailureCode.SKY_PROFILE_FAILURE: "fail",
    FailureCode.LIGHTING_PROFILE_FAILURE: "fail",
    FailureCode.FOG_PROFILE_FAILURE: "fail",
    FailureCode.ATMOSPHERE_PROFILE_FAILURE: "fail",
    FailureCode.VISIBILITY_MINIMUM_VIOLATED: "fail",
    FailureCode.EXPOSURE_OUT_OF_RANGE: "fail",
    FailureCode.POI_USABILITY_FAILURE: "fail",
    FailureCode.LEVEL_DESIGN_FAILURE: "fail",
    FailureCode.REACHABILITY_FAILURE: "fail",
    FailureCode.POI_GRAPH_FAILURE: "fail",
    FailureCode.POI_PLACEMENT_INVALID: "fail",
    FailureCode.ENTITY_ANCHOR_FAILURE: "fail",
    FailureCode.NPC_SPAWN_FAILURE: "fail",
    FailureCode.ENCOUNTER_READINESS_FAILURE: "fail",
    FailureCode.ENTITY_DENSITY_EXCEEDED: "fail",
    FailureCode.RENDERING_PROFILE_FAILURE: "fail",
    FailureCode.SCALABILITY_FAILURE: "fail",
    FailureCode.RAYTRACING_FAILURE: "fail",
    FailureCode.BUDGET_FAILURE: "fail",
    FailureCode.FRAME_RISK_EXCEEDED: "fail",
    FailureCode.SCENARIO_FAILURE: "fail",
    FailureCode.PACKAGE_FAILURE: "fail",
    FailureCode.LIFECYCLE_FAILURE: "fail",
    FailureCode.DETERMINISM_FAILURE: "fail",
    FailureCode.REGRESSION_FAILURE: "fail",
    FailureCode.FUZZ_FAILURE: "fail",
    FailureCode.CORRUPTION_UNDETECTED: "fail",
    FailureCode.REPAIR_TOUCHED_HUMAN_OWNED: "fail",
    # v1.1 BiomeForge gate-level codes — every gate failure is blocking.
    FailureCode.BIOME_CONTRACT_FAILURE: "fail",
    FailureCode.BIOME_MATRIX_FAILURE: "fail",
    FailureCode.BIOME_PROFILE_BINDING_FAILURE: "fail",
    FailureCode.BIOME_ENVIRONMENT_COMPATIBILITY_FAILURE: "fail",
    FailureCode.TERRAIN_FORM_FAILURE: "fail",
    FailureCode.MATERIAL_FAMILY_FAILURE: "fail",
    FailureCode.VEGETATION_PROFILE_FAILURE: "fail",
    FailureCode.PLACEMENT_PROFILE_FAILURE: "fail",
    FailureCode.BIOME_POI_COMPATIBILITY_FAILURE: "fail",
    FailureCode.BIOME_TRAVERSAL_FAILURE: "fail",
    FailureCode.BIOME_ECOLOGY_FAILURE: "fail",
    FailureCode.BIOME_BUDGET_FAILURE: "fail",
    FailureCode.BIOME_PACKAGE_FAILURE: "fail",
    FailureCode.BIOME_FUZZ_FAILURE: "fail",
    # v1.2 MeshForge Intake gate-level codes — every gate failure is blocking.
    FailureCode.MESH_CONTRACT_FAILURE: "fail",
    FailureCode.MESH_CATALOG_FAILURE: "fail",
    FailureCode.MESH_PROVENANCE_FAILURE: "fail",
    FailureCode.MESH_OWNERSHIP_FAILURE: "fail",
    FailureCode.MESH_FINAL_PATH_FAILURE: "fail",
    FailureCode.MESH_SOURCE_FAILURE: "fail",
    FailureCode.MESH_MATERIAL_BINDING_FAILURE: "fail",
    FailureCode.MESH_COLLISION_FAILURE: "fail",
    FailureCode.MESH_BOUNDS_FAILURE: "fail",
    FailureCode.MESH_PIVOT_FAILURE: "fail",
    FailureCode.MESH_SCALE_FAILURE: "fail",
    FailureCode.MESH_PCG_ELIGIBILITY_FAILURE: "fail",
    FailureCode.MESH_BIOME_COMPATIBILITY_FAILURE: "fail",
    FailureCode.MESH_RENDERING_BUDGET_FAILURE: "fail",
    FailureCode.MESH_PACKAGE_FAILURE: "fail",
    FailureCode.MESH_LIFECYCLE_FAILURE: "fail",
    FailureCode.MESH_REPAIR_FAILURE: "fail",
    FailureCode.MESH_DESTROY_FAILURE: "fail",
    FailureCode.MESH_NEGATIVE_FIXTURE_FAILURE: "fail",
    # v1.2 addendum — Houdini intake codes (all blocking).
    FailureCode.HOUDINI_SOURCE_FAILURE: "fail",
    FailureCode.HOUDINI_HDA_OWNERSHIP_FAILURE: "fail",
    FailureCode.HOUDINI_PARAMETER_FAILURE: "fail",
    FailureCode.HOUDINI_COOK_FAILURE: "fail",
    FailureCode.HOUDINI_BAKE_FAILURE: "fail",
    FailureCode.HOUDINI_IMPORT_FAILURE: "fail",
    FailureCode.HOUDINI_OUTPUT_REGISTRY_FAILURE: "fail",
    FailureCode.HOUDINI_OUTPUT_PROVENANCE_FAILURE: "fail",
    FailureCode.HOUDINI_OUTPUT_PACKAGE_FAILURE: "fail",
    # v1.2 addendum — Megascans / external-asset codes (all blocking).
    FailureCode.MEGASCANS_LIBRARY_FAILURE: "fail",
    FailureCode.MEGASCANS_SCAN_FAILURE: "fail",
    FailureCode.MEGASCANS_CATALOG_FAILURE: "fail",
    FailureCode.MEGASCANS_BINDING_FAILURE: "fail",
    FailureCode.MEGASCANS_PCG_ELIGIBILITY_FAILURE: "fail",
    FailureCode.MEGASCANS_BIOME_COMPATIBILITY_FAILURE: "fail",
    FailureCode.EXTERNAL_ASSET_OWNERSHIP_FAILURE: "fail",
    FailureCode.EXTERNAL_LICENSE_METADATA_FAILURE: "fail",
    FailureCode.THIRD_PARTY_ASSET_DESTROY_RISK: "fail",
    FailureCode.THIRD_PARTY_ASSET_PACKAGE_POLICY_FAILURE: "fail",
    FailureCode.DERIVED_OUTPUT_PROVENANCE_FAILURE: "fail",
    FailureCode.SOURCE_OWNERSHIP_SEPARATION_FAILURE: "fail",
    # v1.3 MissionForge + PlaytestForge codes (all blocking).
    FailureCode.MISSION_CONTRACT_FAILURE: "fail",
    FailureCode.MISSION_GRAPH_FAILURE: "fail",
    FailureCode.MISSION_PLACEMENT_FAILURE: "fail",
    FailureCode.MISSION_ROUTE_FAILURE: "fail",
    FailureCode.MISSION_OBJECTIVE_FAILURE: "fail",
    FailureCode.MISSION_STATE_FAILURE: "fail",
    FailureCode.MISSION_SAVE_LOAD_FAILURE: "fail",
    FailureCode.MISSION_REWARD_FAILURE: "fail",
    FailureCode.MISSION_BIOME_COMPATIBILITY_FAILURE: "fail",
    FailureCode.MISSION_MESH_DEPENDENCY_FAILURE: "fail",
    FailureCode.PLAYTEST_CONTRACT_FAILURE: "fail",
    FailureCode.PLAYTEST_ROUTE_FAILURE: "fail",
    FailureCode.PLAYTEST_ACTION_FAILURE: "fail",
    FailureCode.PLAYTEST_COMPLETION_FAILURE: "fail",
    FailureCode.PLAYTEST_STATE_TRANSITION_FAILURE: "fail",
    FailureCode.PLAYTEST_SAVE_LOAD_FAILURE: "fail",
    FailureCode.PLAYTEST_REPORT_FAILURE: "fail",
    # v1.3.5 VisualFidelityForge codes (all blocking).
    FailureCode.VISUAL_ASSET_COVERAGE_FAILURE: "fail",
    FailureCode.SURFACE_MATERIALIZATION_FAILURE: "fail",
    FailureCode.WORLD_DRESSING_FAILURE: "fail",
    FailureCode.ENVIRONMENT_RIG_FAILURE: "fail",
    FailureCode.SKY_MATERIALIZATION_FAILURE: "fail",
    FailureCode.FOG_MATERIALIZATION_FAILURE: "fail",
    FailureCode.CLOUD_MATERIALIZATION_FAILURE: "fail",
    FailureCode.LIGHTING_EXPOSURE_FAILURE: "fail",
    FailureCode.POST_PROCESS_PROFILE_FAILURE: "fail",
    FailureCode.WEATHER_VFX_FAILURE: "fail",
    FailureCode.VISUAL_READABILITY_FAILURE: "fail",
    FailureCode.VISUAL_BUDGET_FAILURE: "fail",
    FailureCode.VISUAL_PACKAGE_FAILURE: "fail",
    FailureCode.VISUAL_LIFECYCLE_FAILURE: "fail",
    # v1.4 EncounterForge / PlaytestForge Beta / BalanceForge Alpha (all blocking).
    FailureCode.ENCOUNTER_CONTRACT_FAILURE: "fail",
    FailureCode.ENCOUNTER_ARCHETYPE_FAILURE: "fail",
    FailureCode.ENCOUNTER_SPAWN_GROUP_FAILURE: "fail",
    FailureCode.ENCOUNTER_ANCHOR_FAILURE: "fail",
    FailureCode.ENCOUNTER_ROUTE_FAILURE: "fail",
    FailureCode.ENCOUNTER_PRESSURE_FAILURE: "fail",
    FailureCode.ENCOUNTER_PACING_FAILURE: "fail",
    FailureCode.ENCOUNTER_BIOME_COMPATIBILITY_FAILURE: "fail",
    FailureCode.ENCOUNTER_MISSION_COMPATIBILITY_FAILURE: "fail",
    FailureCode.ENCOUNTER_MESH_DEPENDENCY_FAILURE: "fail",
    FailureCode.ENCOUNTER_STATE_FAILURE: "fail",
    FailureCode.ENCOUNTER_SAVE_LOAD_FAILURE: "fail",
    FailureCode.ENCOUNTER_REWARD_FAILURE: "fail",
    FailureCode.ENCOUNTER_BALANCE_FAILURE: "fail",
    FailureCode.ENCOUNTER_PACKAGE_FAILURE: "fail",
    FailureCode.ENCOUNTER_LIFECYCLE_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_CONTRACT_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_ROUTE_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_ENCOUNTER_RESOLUTION_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_PRESSURE_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_COMPLETION_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_SAVE_LOAD_FAILURE: "fail",
    FailureCode.PLAYTEST_BETA_REPORT_FAILURE: "fail",
    FailureCode.BALANCE_CONTRACT_FAILURE: "fail",
    FailureCode.BALANCE_REPORT_FAILURE: "fail",
    # v1.6 — the single honest non-blocking-by-default code: a live-UE gate
    # that cannot run because the editor bridge is offline. WARN => blocking
    # under STRICT (so the shield is never falsely green) but non-blocking
    # otherwise (so the authoring substrate can be proven without the editor).
    # It NEVER counts as runtime completion — see PlaytestForge Gamma.
    FailureCode.RUNTIME_LIVE_RUN_PENDING: "warn",
}

# The v1.0x gate-level failure taxonomy (brief §"shared failure taxonomy"):
# one code per full-shield gate class, used by full-shield to roll failures up
# by lane. Keyed by the human name in the brief -> stable code.
GATE_TAXONOMY = {
    "CONTRACT_FAILURE": FailureCode.CONTRACT_FAILURE,
    "GENERATION_FAILURE": FailureCode.GENERATION_FAILURE,
    "ASSET_REFERENCE_FAILURE": FailureCode.ASSET_REFERENCE_FAILURE,
    "OWNERSHIP_FAILURE": FailureCode.OWNERSHIP_FAILURE,
    "ENVIRONMENT_PROFILE_FAILURE": FailureCode.ENVIRONMENT_PROFILE_FAILURE,
    "SKY_PROFILE_FAILURE": FailureCode.SKY_PROFILE_FAILURE,
    "LIGHTING_PROFILE_FAILURE": FailureCode.LIGHTING_PROFILE_FAILURE,
    "FOG_PROFILE_FAILURE": FailureCode.FOG_PROFILE_FAILURE,
    "ATMOSPHERE_PROFILE_FAILURE": FailureCode.ATMOSPHERE_PROFILE_FAILURE,
    "POI_USABILITY_FAILURE": FailureCode.POI_USABILITY_FAILURE,
    "LEVEL_DESIGN_FAILURE": FailureCode.LEVEL_DESIGN_FAILURE,
    "REACHABILITY_FAILURE": FailureCode.REACHABILITY_FAILURE,
    "ENTITY_ANCHOR_FAILURE": FailureCode.ENTITY_ANCHOR_FAILURE,
    "RENDERING_PROFILE_FAILURE": FailureCode.RENDERING_PROFILE_FAILURE,
    "SCALABILITY_FAILURE": FailureCode.SCALABILITY_FAILURE,
    "RAYTRACING_FAILURE": FailureCode.RAYTRACING_FAILURE,
    "BUDGET_FAILURE": FailureCode.BUDGET_FAILURE,
    "SCENARIO_FAILURE": FailureCode.SCENARIO_FAILURE,
    "PACKAGE_FAILURE": FailureCode.PACKAGE_FAILURE,
    "LIFECYCLE_FAILURE": FailureCode.LIFECYCLE_FAILURE,
    "DETERMINISM_FAILURE": FailureCode.DETERMINISM_FAILURE,
    "REPORT_INTEGRITY_FAILURE": FailureCode.REPORT_INTEGRITY_FAILURE,
    "REGRESSION_FAILURE": FailureCode.REGRESSION_FAILURE,
    "FUZZ_FAILURE": FailureCode.FUZZ_FAILURE,
    # v1.1 BiomeForge lane codes.
    "BIOME_CONTRACT_FAILURE": FailureCode.BIOME_CONTRACT_FAILURE,
    "BIOME_MATRIX_FAILURE": FailureCode.BIOME_MATRIX_FAILURE,
    "BIOME_PROFILE_BINDING_FAILURE": FailureCode.BIOME_PROFILE_BINDING_FAILURE,
    "BIOME_ENVIRONMENT_COMPATIBILITY_FAILURE": FailureCode.BIOME_ENVIRONMENT_COMPATIBILITY_FAILURE,
    "TERRAIN_FORM_FAILURE": FailureCode.TERRAIN_FORM_FAILURE,
    "MATERIAL_FAMILY_FAILURE": FailureCode.MATERIAL_FAMILY_FAILURE,
    "VEGETATION_PROFILE_FAILURE": FailureCode.VEGETATION_PROFILE_FAILURE,
    "PLACEMENT_PROFILE_FAILURE": FailureCode.PLACEMENT_PROFILE_FAILURE,
    "BIOME_POI_COMPATIBILITY_FAILURE": FailureCode.BIOME_POI_COMPATIBILITY_FAILURE,
    "BIOME_TRAVERSAL_FAILURE": FailureCode.BIOME_TRAVERSAL_FAILURE,
    "BIOME_ECOLOGY_FAILURE": FailureCode.BIOME_ECOLOGY_FAILURE,
    "BIOME_BUDGET_FAILURE": FailureCode.BIOME_BUDGET_FAILURE,
    "BIOME_PACKAGE_FAILURE": FailureCode.BIOME_PACKAGE_FAILURE,
    "BIOME_FUZZ_FAILURE": FailureCode.BIOME_FUZZ_FAILURE,
    # v1.2 MeshForge Intake lane codes.
    "MESH_CONTRACT_FAILURE": FailureCode.MESH_CONTRACT_FAILURE,
    "MESH_CATALOG_FAILURE": FailureCode.MESH_CATALOG_FAILURE,
    "MESH_PROVENANCE_FAILURE": FailureCode.MESH_PROVENANCE_FAILURE,
    "MESH_OWNERSHIP_FAILURE": FailureCode.MESH_OWNERSHIP_FAILURE,
    "MESH_FINAL_PATH_FAILURE": FailureCode.MESH_FINAL_PATH_FAILURE,
    "MESH_SOURCE_FAILURE": FailureCode.MESH_SOURCE_FAILURE,
    "MESH_MATERIAL_BINDING_FAILURE": FailureCode.MESH_MATERIAL_BINDING_FAILURE,
    "MESH_COLLISION_FAILURE": FailureCode.MESH_COLLISION_FAILURE,
    "MESH_BOUNDS_FAILURE": FailureCode.MESH_BOUNDS_FAILURE,
    "MESH_PIVOT_FAILURE": FailureCode.MESH_PIVOT_FAILURE,
    "MESH_SCALE_FAILURE": FailureCode.MESH_SCALE_FAILURE,
    "MESH_PCG_ELIGIBILITY_FAILURE": FailureCode.MESH_PCG_ELIGIBILITY_FAILURE,
    "MESH_BIOME_COMPATIBILITY_FAILURE": FailureCode.MESH_BIOME_COMPATIBILITY_FAILURE,
    "MESH_RENDERING_BUDGET_FAILURE": FailureCode.MESH_RENDERING_BUDGET_FAILURE,
    "MESH_PACKAGE_FAILURE": FailureCode.MESH_PACKAGE_FAILURE,
    "MESH_LIFECYCLE_FAILURE": FailureCode.MESH_LIFECYCLE_FAILURE,
    "MESH_REPAIR_FAILURE": FailureCode.MESH_REPAIR_FAILURE,
    "MESH_DESTROY_FAILURE": FailureCode.MESH_DESTROY_FAILURE,
    "MESH_NEGATIVE_FIXTURE_FAILURE": FailureCode.MESH_NEGATIVE_FIXTURE_FAILURE,
    # v1.2 addendum — Houdini lane codes.
    "HOUDINI_SOURCE_FAILURE": FailureCode.HOUDINI_SOURCE_FAILURE,
    "HOUDINI_HDA_OWNERSHIP_FAILURE": FailureCode.HOUDINI_HDA_OWNERSHIP_FAILURE,
    "HOUDINI_PARAMETER_FAILURE": FailureCode.HOUDINI_PARAMETER_FAILURE,
    "HOUDINI_COOK_FAILURE": FailureCode.HOUDINI_COOK_FAILURE,
    "HOUDINI_BAKE_FAILURE": FailureCode.HOUDINI_BAKE_FAILURE,
    "HOUDINI_IMPORT_FAILURE": FailureCode.HOUDINI_IMPORT_FAILURE,
    "HOUDINI_OUTPUT_REGISTRY_FAILURE": FailureCode.HOUDINI_OUTPUT_REGISTRY_FAILURE,
    "HOUDINI_OUTPUT_PROVENANCE_FAILURE": FailureCode.HOUDINI_OUTPUT_PROVENANCE_FAILURE,
    "HOUDINI_OUTPUT_PACKAGE_FAILURE": FailureCode.HOUDINI_OUTPUT_PACKAGE_FAILURE,
    # v1.2 addendum — Megascans / external-asset lane codes.
    "MEGASCANS_LIBRARY_FAILURE": FailureCode.MEGASCANS_LIBRARY_FAILURE,
    "MEGASCANS_SCAN_FAILURE": FailureCode.MEGASCANS_SCAN_FAILURE,
    "MEGASCANS_CATALOG_FAILURE": FailureCode.MEGASCANS_CATALOG_FAILURE,
    "MEGASCANS_BINDING_FAILURE": FailureCode.MEGASCANS_BINDING_FAILURE,
    "MEGASCANS_PCG_ELIGIBILITY_FAILURE": FailureCode.MEGASCANS_PCG_ELIGIBILITY_FAILURE,
    "MEGASCANS_BIOME_COMPATIBILITY_FAILURE": FailureCode.MEGASCANS_BIOME_COMPATIBILITY_FAILURE,
    "EXTERNAL_ASSET_OWNERSHIP_FAILURE": FailureCode.EXTERNAL_ASSET_OWNERSHIP_FAILURE,
    "EXTERNAL_LICENSE_METADATA_FAILURE": FailureCode.EXTERNAL_LICENSE_METADATA_FAILURE,
    "THIRD_PARTY_ASSET_DESTROY_RISK": FailureCode.THIRD_PARTY_ASSET_DESTROY_RISK,
    "THIRD_PARTY_ASSET_PACKAGE_POLICY_FAILURE": FailureCode.THIRD_PARTY_ASSET_PACKAGE_POLICY_FAILURE,
    "DERIVED_OUTPUT_PROVENANCE_FAILURE": FailureCode.DERIVED_OUTPUT_PROVENANCE_FAILURE,
    "SOURCE_OWNERSHIP_SEPARATION_FAILURE": FailureCode.SOURCE_OWNERSHIP_SEPARATION_FAILURE,
    # v1.3 MissionForge + PlaytestForge lane codes.
    "MISSION_CONTRACT_FAILURE": FailureCode.MISSION_CONTRACT_FAILURE,
    "MISSION_GRAPH_FAILURE": FailureCode.MISSION_GRAPH_FAILURE,
    "MISSION_PLACEMENT_FAILURE": FailureCode.MISSION_PLACEMENT_FAILURE,
    "MISSION_ROUTE_FAILURE": FailureCode.MISSION_ROUTE_FAILURE,
    "MISSION_OBJECTIVE_FAILURE": FailureCode.MISSION_OBJECTIVE_FAILURE,
    "MISSION_STATE_FAILURE": FailureCode.MISSION_STATE_FAILURE,
    "MISSION_SAVE_LOAD_FAILURE": FailureCode.MISSION_SAVE_LOAD_FAILURE,
    "MISSION_REWARD_FAILURE": FailureCode.MISSION_REWARD_FAILURE,
    "MISSION_BIOME_COMPATIBILITY_FAILURE": FailureCode.MISSION_BIOME_COMPATIBILITY_FAILURE,
    "MISSION_MESH_DEPENDENCY_FAILURE": FailureCode.MISSION_MESH_DEPENDENCY_FAILURE,
    "PLAYTEST_CONTRACT_FAILURE": FailureCode.PLAYTEST_CONTRACT_FAILURE,
    "PLAYTEST_ROUTE_FAILURE": FailureCode.PLAYTEST_ROUTE_FAILURE,
    "PLAYTEST_ACTION_FAILURE": FailureCode.PLAYTEST_ACTION_FAILURE,
    "PLAYTEST_COMPLETION_FAILURE": FailureCode.PLAYTEST_COMPLETION_FAILURE,
    "PLAYTEST_STATE_TRANSITION_FAILURE": FailureCode.PLAYTEST_STATE_TRANSITION_FAILURE,
    "PLAYTEST_SAVE_LOAD_FAILURE": FailureCode.PLAYTEST_SAVE_LOAD_FAILURE,
    "PLAYTEST_REPORT_FAILURE": FailureCode.PLAYTEST_REPORT_FAILURE,
    # v1.3.5 VisualFidelityForge lane codes.
    "VISUAL_ASSET_COVERAGE_FAILURE": FailureCode.VISUAL_ASSET_COVERAGE_FAILURE,
    "SURFACE_MATERIALIZATION_FAILURE": FailureCode.SURFACE_MATERIALIZATION_FAILURE,
    "WORLD_DRESSING_FAILURE": FailureCode.WORLD_DRESSING_FAILURE,
    "ENVIRONMENT_RIG_FAILURE": FailureCode.ENVIRONMENT_RIG_FAILURE,
    "SKY_MATERIALIZATION_FAILURE": FailureCode.SKY_MATERIALIZATION_FAILURE,
    "FOG_MATERIALIZATION_FAILURE": FailureCode.FOG_MATERIALIZATION_FAILURE,
    "CLOUD_MATERIALIZATION_FAILURE": FailureCode.CLOUD_MATERIALIZATION_FAILURE,
    "LIGHTING_EXPOSURE_FAILURE": FailureCode.LIGHTING_EXPOSURE_FAILURE,
    "POST_PROCESS_PROFILE_FAILURE": FailureCode.POST_PROCESS_PROFILE_FAILURE,
    "WEATHER_VFX_FAILURE": FailureCode.WEATHER_VFX_FAILURE,
    "VISUAL_READABILITY_FAILURE": FailureCode.VISUAL_READABILITY_FAILURE,
    "VISUAL_BUDGET_FAILURE": FailureCode.VISUAL_BUDGET_FAILURE,
    "VISUAL_PACKAGE_FAILURE": FailureCode.VISUAL_PACKAGE_FAILURE,
    "VISUAL_LIFECYCLE_FAILURE": FailureCode.VISUAL_LIFECYCLE_FAILURE,
    # v1.4 EncounterForge / PlaytestForge Beta / BalanceForge Alpha
    "ENCOUNTER_CONTRACT_FAILURE": FailureCode.ENCOUNTER_CONTRACT_FAILURE,
    "ENCOUNTER_ARCHETYPE_FAILURE": FailureCode.ENCOUNTER_ARCHETYPE_FAILURE,
    "ENCOUNTER_SPAWN_GROUP_FAILURE": FailureCode.ENCOUNTER_SPAWN_GROUP_FAILURE,
    "ENCOUNTER_ANCHOR_FAILURE": FailureCode.ENCOUNTER_ANCHOR_FAILURE,
    "ENCOUNTER_ROUTE_FAILURE": FailureCode.ENCOUNTER_ROUTE_FAILURE,
    "ENCOUNTER_PRESSURE_FAILURE": FailureCode.ENCOUNTER_PRESSURE_FAILURE,
    "ENCOUNTER_PACING_FAILURE": FailureCode.ENCOUNTER_PACING_FAILURE,
    "ENCOUNTER_BIOME_COMPATIBILITY_FAILURE": FailureCode.ENCOUNTER_BIOME_COMPATIBILITY_FAILURE,
    "ENCOUNTER_MISSION_COMPATIBILITY_FAILURE": FailureCode.ENCOUNTER_MISSION_COMPATIBILITY_FAILURE,
    "ENCOUNTER_MESH_DEPENDENCY_FAILURE": FailureCode.ENCOUNTER_MESH_DEPENDENCY_FAILURE,
    "ENCOUNTER_STATE_FAILURE": FailureCode.ENCOUNTER_STATE_FAILURE,
    "ENCOUNTER_SAVE_LOAD_FAILURE": FailureCode.ENCOUNTER_SAVE_LOAD_FAILURE,
    "ENCOUNTER_REWARD_FAILURE": FailureCode.ENCOUNTER_REWARD_FAILURE,
    "ENCOUNTER_BALANCE_FAILURE": FailureCode.ENCOUNTER_BALANCE_FAILURE,
    "ENCOUNTER_PACKAGE_FAILURE": FailureCode.ENCOUNTER_PACKAGE_FAILURE,
    "ENCOUNTER_LIFECYCLE_FAILURE": FailureCode.ENCOUNTER_LIFECYCLE_FAILURE,
    "PLAYTEST_BETA_CONTRACT_FAILURE": FailureCode.PLAYTEST_BETA_CONTRACT_FAILURE,
    "PLAYTEST_BETA_ROUTE_FAILURE": FailureCode.PLAYTEST_BETA_ROUTE_FAILURE,
    "PLAYTEST_BETA_ENCOUNTER_RESOLUTION_FAILURE": FailureCode.PLAYTEST_BETA_ENCOUNTER_RESOLUTION_FAILURE,
    "PLAYTEST_BETA_PRESSURE_FAILURE": FailureCode.PLAYTEST_BETA_PRESSURE_FAILURE,
    "PLAYTEST_BETA_COMPLETION_FAILURE": FailureCode.PLAYTEST_BETA_COMPLETION_FAILURE,
    "PLAYTEST_BETA_SAVE_LOAD_FAILURE": FailureCode.PLAYTEST_BETA_SAVE_LOAD_FAILURE,
    "PLAYTEST_BETA_REPORT_FAILURE": FailureCode.PLAYTEST_BETA_REPORT_FAILURE,
    "BALANCE_CONTRACT_FAILURE": FailureCode.BALANCE_CONTRACT_FAILURE,
    "BALANCE_REPORT_FAILURE": FailureCode.BALANCE_REPORT_FAILURE,
}


# --- completeness backfill (v1.5) -----------------------------------------
# Every defined code MUST have a severity (default: blocking) and appear in the
# gate taxonomy so full-shield rolls it up by lane and validate_failure_codes can
# prove no code is orphaned. Earlier bands enumerate these explicitly above; this
# backfill covers the v1.5 bands without 60 hand-written lines and stays correct
# as codes are added. It never overrides an explicit severity already set above.
for _name, _code in list(vars(FailureCode).items()):
    if _name.startswith("_") or not isinstance(_code, str):
        continue
    SEVERITY.setdefault(_code, "fail")
    GATE_TAXONOMY.setdefault(_name, _code)
del _name, _code


def all_codes():
    """Return every defined code string (for tests / docs generation)."""
    return [v for k, v in vars(FailureCode).items()
            if not k.startswith("_") and isinstance(v, str)]


def code_number(code):
    """Return the integer band number of a WFnnn_* code, or -1 if malformed."""
    try:
        return int(str(code)[2:5])
    except (ValueError, IndexError):
        return -1


def severity_of(code):
    """Return the default severity bucket for a code, or 'fail' if unknown."""
    return SEVERITY.get(code, "fail")
