#!/usr/bin/env python3
"""npc_pack.py — WorldForge v1.7 NPCForge shared pack model + canonical definitions.

One place for (a) reading the existing v1.4 encounter catalog and the v1.6z
grounded route substrate a behavior scenario binds to, and (b) the canonical NPC
archetype / perception / pressure / behavior-profile definitions the generators
emit. Keeping the definitions here (as data) means every generator and validator
agrees on ids, and the mapping from the 8 v1.4 encounter archetypes to behavior is
single-sourced and auditable.

Data it reads (all already generated by prior milestones):
  procedural/generated/encounters/<encounter_id>/encounter.json   (v1.4)
  procedural/generated/ground/route_plans/<scenario_id>.json      (v1.6z)
  procedural/generated/ground/route_graphs/<map_id>.json          (v1.6z)
"""
import json
from pathlib import Path

import npc_contracts as NX

REPO_ROOT = Path(__file__).resolve().parents[2]
GEN = REPO_ROOT / "procedural" / "generated"
ENCOUNTERS_DIR = GEN / "encounters"
ROUTE_PLANS_DIR = GEN / "ground" / "route_plans"
ROUTE_GRAPHS_DIR = GEN / "ground" / "route_graphs"

CREATED_BY = "worldforge.v1.7"
CREATED_AT = "2026-07-08T00:00:00+00:00"


# --------------------------------------------------------------------------- #
# Canonical NPC archetype definitions (behavior_role -> archetype fields).
# Movement/pressure/perception are grounded-substrate only. engagement <
# disengagement (hysteresis). can_block_route defaults false to protect the
# mission path; only guard_zone holders may transiently block.
# --------------------------------------------------------------------------- #
ARCHETYPE_DEFS = {
    "grunt_patroller": dict(
        movement_model="patrol_route", pressure_model="proximity_pressure",
        perception_model="perc_standard_radius", route_modes=["grounded_worldforge_route"],
        spawn_zones=["walkable_off_route"], engagement=800.0, disengagement=1200.0,
        speed=300.0, can_block=False, block_policy="never", balance=["low_pressure"], los=False),
    "static_guard": dict(
        movement_model="guard_radius", pressure_model="proximity_pressure",
        perception_model="perc_standard_radius", route_modes=["grounded_manual_waypoint"],
        spawn_zones=["walkable_off_route", "anchor_bound"], engagement=700.0, disengagement=1000.0,
        speed=200.0, can_block=True, block_policy="guard_zone_only", balance=["medium_pressure"], los=False),
    "ranged_sentry": dict(
        movement_model="stationary", pressure_model="ranged_tick_pressure",
        perception_model="perc_long_los", route_modes=["stationary_anchor"],
        spawn_zones=["anchor_bound"], engagement=1400.0, disengagement=1800.0,
        speed=0.0, can_block=False, block_policy="never", balance=["ranged_pressure"], los=True),
    "hazard_warden": dict(
        movement_model="hazard_anchor", pressure_model="hazard_zone_pressure",
        perception_model="perc_short", route_modes=["stationary_anchor"],
        spawn_zones=["anchor_bound"], engagement=500.0, disengagement=700.0,
        speed=0.0, can_block=False, block_policy="never", balance=["hazard_pressure"], los=False),
    "ambush_trigger": dict(
        movement_model="triggered_ambush", pressure_model="contact_pressure",
        perception_model="perc_trigger", route_modes=["grounded_manual_waypoint"],
        spawn_zones=["anchor_bound"], engagement=400.0, disengagement=900.0,
        speed=350.0, can_block=False, block_policy="never", balance=["burst_pressure"], los=False),
    "heavy_blocker": dict(
        movement_model="guard_radius", pressure_model="contact_pressure",
        perception_model="perc_standard_radius", route_modes=["grounded_manual_waypoint"],
        spawn_zones=["walkable_off_route", "anchor_bound"], engagement=600.0, disengagement=900.0,
        speed=180.0, can_block=True, block_policy="guard_zone_only", balance=["high_pressure"], los=False),
    "scout_chaser": dict(
        movement_model="pursue_limited", pressure_model="proximity_pressure",
        perception_model="perc_wide", route_modes=["grounded_worldforge_route"],
        spawn_zones=["walkable_off_route"], engagement=1000.0, disengagement=1500.0,
        speed=420.0, can_block=False, block_policy="never", balance=["medium_pressure"], los=False),
}

# Canonical perception models referenced above.
PERCEPTION_DEFS = {
    "perc_standard_radius": dict(radius=800.0, fov=200.0, los=False, hearing=600.0, memory=4.0,
                                 interval=0.25, occ="none", detect=0.6, loss=0.3),
    "perc_long_los": dict(radius=1400.0, fov=90.0, los=True, hearing=400.0, memory=6.0,
                          interval=0.2, occ="line_trace", detect=0.7, loss=0.4),
    "perc_short": dict(radius=500.0, fov=360.0, los=False, hearing=300.0, memory=2.0,
                       interval=0.5, occ="none", detect=0.5, loss=0.25),
    "perc_trigger": dict(radius=400.0, fov=360.0, los=False, hearing=200.0, memory=1.0,
                         interval=0.1, occ="none", detect=0.8, loss=0.5),
    "perc_wide": dict(radius=1000.0, fov=270.0, los=False, hearing=800.0, memory=5.0,
                      interval=0.25, occ="none", detect=0.55, loss=0.3),
}

# Canonical pressure models (one per pressure_model an archetype uses).
PRESSURE_DEFS = {
    "proximity_pressure": dict(ptype="state_pressure", radius=600.0, tick=0.5, value=4.0,
                               maxdur=20.0, cooldown=3.0, los=False,
                               effects=["alert_raised"], events=["behavior.pressure.applied",
                                                                 "behavior.pressure.expired"]),
    "ranged_tick_pressure": dict(ptype="state_pressure", radius=1400.0, tick=0.75, value=3.0,
                                 maxdur=25.0, cooldown=4.0, los=True,
                                 effects=["suppressed"], events=["behavior.pressure.applied",
                                                                 "behavior.pressure.expired"]),
    "hazard_zone_pressure": dict(ptype="hazard_exposure", radius=500.0, tick=0.5, value=5.0,
                                 maxdur=15.0, cooldown=2.0, los=False,
                                 effects=["hazard_exposed"], events=["behavior.pressure.applied",
                                                                     "behavior.pressure.expired"]),
    "contact_pressure": dict(ptype="state_pressure", radius=250.0, tick=0.25, value=6.0,
                             maxdur=10.0, cooldown=5.0, los=False,
                             effects=["struck"], events=["behavior.pressure.applied",
                                                         "behavior.pressure.expired"]),
}

# The 8 v1.4 encounter archetypes -> behavior profile kind + NPC archetype roster.
# Every v1.4 archetype maps to behavior — none silently unsupported (STRICT rule).
ENCOUNTER_BEHAVIOR_MAP = {
    "guarded_objective": ("guard_pressure", ["static_guard", "ranged_sentry"]),
    "patrol_route": ("patrol_pressure", ["grunt_patroller"]),
    "ambush_choke": ("ambush_pressure", ["ambush_trigger"]),
    "hazard_field": ("hazard_pressure", ["hazard_warden"]),
    "resource_contest": ("guard_pressure", ["static_guard", "grunt_patroller"]),
    "defensive_holdout": ("guard_pressure", ["static_guard", "heavy_blocker"]),
    "roaming_threat": ("patrol_pressure", ["grunt_patroller", "scout_chaser"]),
    "extraction_pressure": ("ranged_pressure", ["ranged_sentry", "grunt_patroller"]),
}


def archetype_id(role):
    return "npc_{}".format(role)


def profile_id(kind):
    return "bp_{}".format(kind)


# --------------------------------------------------------------------------- #
# Emitters — build a validated-shape contract dict from the canonical defs.
# --------------------------------------------------------------------------- #
def build_archetype(role):
    d = ARCHETYPE_DEFS[role]
    return {
        "npc_archetype_id": archetype_id(role), "display_name": role.replace("_", " ").title(),
        "behavior_role": role, "movement_model": d["movement_model"],
        "perception_model": d["perception_model"], "pressure_model": d["pressure_model"],
        "allowed_spawn_zones": list(d["spawn_zones"]), "allowed_route_modes": list(d["route_modes"]),
        "collision_profile": "Pawn", "capsule_radius": 34.0, "capsule_half_height": 88.0,
        "movement_speed": d["speed"], "engagement_radius": d["engagement"],
        "disengagement_radius": d["disengagement"], "line_of_sight_required": d["los"],
        "can_block_route": d["can_block"], "route_blocking_policy": d["block_policy"],
        "save_load_required": True, "telemetry_required": True, "balance_tags": list(d["balance"]),
        "validation_requirements": ["spawn_walkable", "route_bound", "telemetry", "save_load"],
        "created_by": CREATED_BY, "created_at": CREATED_AT, "schema_version": NX.ARCHETYPE_SCHEMA_VERSION,
    }


def build_perception(pid):
    d = PERCEPTION_DEFS[pid]
    return {
        "perception_model_id": pid, "radius": d["radius"], "field_of_view_degrees": d["fov"],
        "line_of_sight_required": d["los"], "hearing_radius": d["hearing"], "memory_seconds": d["memory"],
        "update_interval_seconds": d["interval"], "occlusion_policy": d["occ"],
        "detection_threshold": d["detect"], "loss_threshold": d["loss"],
        "schema_version": NX.PERCEPTION_SCHEMA_VERSION, "created_by": CREATED_BY, "created_at": CREATED_AT,
    }


def build_pressure(pid):
    d = PRESSURE_DEFS[pid]
    return {
        "pressure_model_id": "prs_{}".format(pid), "pressure_type": d["ptype"], "radius": d["radius"],
        "tick_interval_seconds": d["tick"], "pressure_value": d["value"],
        "max_pressure_duration": d["maxdur"], "cooldown_seconds": d["cooldown"],
        "requires_line_of_sight": d["los"], "state_effects": list(d["effects"]),
        "telemetry_events": list(d["events"]), "schema_version": NX.PRESSURE_SCHEMA_VERSION,
        "created_by": CREATED_BY, "created_at": CREATED_AT,
    }


# --------------------------------------------------------------------------- #
# Readers — the existing substrate.
# --------------------------------------------------------------------------- #
def iter_encounters(pack):
    """Yield (encounter_id, encounter_dict) for every encounter in the pack."""
    out = []
    if not ENCOUNTERS_DIR.is_dir():
        return out
    for d in sorted(ENCOUNTERS_DIR.iterdir()):
        f = d / "encounter.json"
        if not f.is_file():
            continue
        try:
            enc = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue
        if enc.get("pack_id") == pack:
            out.append((enc.get("encounter_id"), enc))
    return out


def load_route_plans():
    """Return {scenario_id: route_plan_dict} over all v1.6z route plans."""
    plans = {}
    if not ROUTE_PLANS_DIR.is_dir():
        return plans
    for f in sorted(ROUTE_PLANS_DIR.glob("rt_*.json")):
        try:
            p = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue
        sid = p.get("scenario_id")
        if sid:
            plans[sid] = p
    return plans


def load_route_graph(map_id):
    f = ROUTE_GRAPHS_DIR / "{}.json".format(map_id)
    if not f.is_file():
        return None
    try:
        return json.loads(f.read_text(encoding="utf-8"))
    except Exception:
        return None


def route_plan_for_encounter(plans, encounter_id, pressure_profile):
    """Find the grounded route plan that grounds this encounter+profile.

    Route plan scenario ids look like rt_<encounter_id>__<pressure_profile>.
    """
    sid = "rt_{}__{}".format(encounter_id, pressure_profile)
    return sid, plans.get(sid)
