#!/usr/bin/env python3
"""reward_forge.py — WorldForge v1.9 deterministic reward/progression dataset spine.

One source of truth for the whole v1.9 authoring dataset so every generator,
validator, and (Wave R) the runtime bridge draw the SAME equipment catalog,
unlock catalog, reward tables, and grant/state derivation. Everything here is
deterministic: fixed timestamps, ids-derived ordering, no wall-clock / RNG — the
same inputs always produce byte-identical records, which is what lets the
determinism and report-integrity gates hold.

Layers:
  * EQUIPMENT_CATALOG / build_equipment_catalog()  — bounded EquipmentItem set
  * UNLOCK_CATALOG / build_unlock_catalog()         — unlock DEFINITIONS
  * build_loadout_profiles()                        — a few LoadoutProfiles
  * build_reward_tables()                           — one table per archetype×risk
  * simulate_grant(table, ...)                      — deterministic grant -> event
  * derive_states(grants)                           — Inventory/Progression/Unlock
  * save_load_roundtrip(state, kind)                — model-level persistence proof
  * classify_risk_reward(...)                       — risk/reward classification

The grant simulation and state derivation here are the AUTHORING-side model:
they produce contract-valid evidence marked ``created_at="authoring"`` so the
Wave-2 validators have real data to gate. The Wave-R runtime bridge produces the
``created_at="live"`` runtime evidence the ``--require-live`` shield lane needs;
both share this module's derivation so authoring and runtime can never disagree
about what a given reward SHOULD do to state.
"""
import hashlib
from pathlib import Path

import reward_contracts as RX
from report_meta import build_meta

REPO_ROOT = Path(__file__).resolve().parents[2]
PACK = "encounter_loop_world"
CREATED_BY = "worldforge.v1.9"
CREATED_AT_AUTHORING = "2026-07-09T00:00:00+00:00"
PLAYER_ID = "player_pack"

# Real combat profile ids generated by v1.8 (cycled to bind reward tables to a
# genuine combat pressure shape). Discovered at import from committed evidence so
# the binding tracks the pack, with a stable fallback if evidence is absent.
_COMBAT_PROFILE_DIR = REPO_ROOT / "procedural/generated/combat/profiles"


def _real_combat_profile_ids():
    ids = []
    if _COMBAT_PROFILE_DIR.is_dir():
        ids = [p.stem for p in sorted(_COMBAT_PROFILE_DIR.glob("cp_*.json"))]
    return ids or ["cp_guard_pressure_guarded_objective"]


COMBAT_PROFILE_IDS = _real_combat_profile_ids()


# --------------------------------------------------------------------------- #
# Equipment catalog — deterministic, bounded. (id, type, name, slot, rarity,
# power, risk, tags). Only slots that exist are used.
# --------------------------------------------------------------------------- #
_EQUIPMENT_SPEC = [
    ("eq_rifle_std", "weapon", "Standard Rifle", "primary", "common", 20.0, 5.0, ["ranged", "starter"]),
    ("eq_rifle_hv", "weapon", "Heavy Rifle", "primary", "rare", 40.0, 12.0, ["ranged", "reward"]),
    ("eq_sidearm_std", "weapon", "Sidearm", "secondary", "common", 10.0, 3.0, ["ranged", "starter"]),
    ("eq_marksman", "weapon", "Marksman Rifle", "secondary", "uncommon", 26.0, 8.0, ["ranged", "reward"]),
    ("eq_scanner", "tool", "Field Scanner", "tool", "common", 5.0, 1.0, ["utility", "starter"]),
    ("eq_breacher", "tool", "Breacher Kit", "tool", "uncommon", 12.0, 4.0, ["utility", "reward"]),
    ("eq_medkit", "consumable", "Medkit", "consumable", "common", 8.0, 0.0, ["heal", "starter"]),
    ("eq_stim", "consumable", "Combat Stim", "consumable", "uncommon", 14.0, 6.0, ["buff", "reward"]),
]


def build_equipment_catalog():
    """Return the deterministic list of contract-valid EquipmentItem dicts."""
    out = []
    for iid, itype, name, slot, rarity, power, risk, tags in _EQUIPMENT_SPEC:
        item = {
            "item_id": iid, "item_type": itype, "display_name": name, "slot": slot,
            "rarity_band": rarity, "power_value": power, "risk_value": risk,
            "allowed_loadout_profiles": [], "allowed_mission_archetypes": list(RX.MISSION_ARCHETYPES),
            "tags": tags, "ownership_class": "generated_owned",
            "provenance": {"generator": "reward_forge", "spec": iid, "seed": 0},
            "created_by": CREATED_BY, "created_at": CREATED_AT_AUTHORING,
            "schema_version": RX.EQUIPMENT_ITEM_SCHEMA_VERSION, "report_type": RX.RT_EQUIPMENT_ITEM,
        }
        out.append(item)
    return out


EQUIPMENT_IDS = tuple(s[0] for s in _EQUIPMENT_SPEC)
REWARD_ITEM_IDS = tuple(s[0] for s in _EQUIPMENT_SPEC if "reward" in s[7])
# Map slot -> a starter item id, for loadout construction.
_STARTER_BY_SLOT = {s[3]: s[0] for s in reversed(_EQUIPMENT_SPEC) if "starter" in s[7]}


# --------------------------------------------------------------------------- #
# Unlock catalog — unlock DEFINITIONS (distinct from runtime UnlockState). Each:
# (unlock_id, unlock_type, affects_generation, display_name).
# --------------------------------------------------------------------------- #
# Six unlock definitions — one per mission archetype, so the high-risk table for
# each archetype grants a DISTINCT unlock and the authoring chain never re-grants
# an already-owned unlock (which would be a no-op, not a real grant).
_UNLOCK_SPEC = [
    ("unl_scout_slot", "loadout_slot", True, "Extra Consumable Slot"),
    ("unl_heavy_rifle", "equipment", True, "Heavy Rifle Access"),
    ("unl_hazard_missions", "mission_archetype", True, "Hazard Mission Access"),
    ("unl_badlands_biome", "biome", True, "Alien Crystal Badlands Access"),
    ("unl_hardened_mod", "modifier", True, "Hardened Loadout Modifier"),
    ("unl_marksman_access", "equipment", True, "Marksman Rifle Access"),
]


def build_unlock_catalog():
    """Return the unlock-definition catalog (a plain dict, not a contract type)."""
    return {
        "schema_version": "wf.reward.unlock_catalog.v1",
        "pack_id": PACK,
        "unlocks": [
            {"unlock_id": uid, "unlock_type": utype, "affects_generation": ag, "display_name": name}
            for uid, utype, ag, name in _UNLOCK_SPEC
        ],
    }


UNLOCK_IDS = tuple(s[0] for s in _UNLOCK_SPEC)


# --------------------------------------------------------------------------- #
# Loadout profiles — a few deterministic profiles from the starter catalog.
# --------------------------------------------------------------------------- #
def build_loadout_profiles():
    prof = {
        "loadout_profile_id": "lo_scout_std", "player_id": PLAYER_ID, "scenario_id": "rs_pack_s0",
        "primary_slot": _STARTER_BY_SLOT.get("primary", "eq_rifle_std"),
        "secondary_slot": _STARTER_BY_SLOT.get("secondary", "eq_sidearm_std"),
        "tool_slot": _STARTER_BY_SLOT.get("tool", "eq_scanner"),
        "consumable_slots": [_STARTER_BY_SLOT.get("consumable", "eq_medkit")],
        "allowed_mission_archetypes": list(RX.MISSION_ARCHETYPES),
        "allowed_biomes": list(RX.KNOWN_BIOMES), "power_budget": 100.0, "risk_budget": 60.0,
        "source": "generated", "created_by": CREATED_BY, "created_at": CREATED_AT_AUTHORING,
        "schema_version": RX.LOADOUT_PROFILE_SCHEMA_VERSION, "report_type": RX.RT_LOADOUT_PROFILE,
    }
    return [prof]


# --------------------------------------------------------------------------- #
# Reward tables — one per (mission_archetype × risk_band) for baseline & high.
# Deterministic: xp scales with risk, high-risk tables add an unlock, budgets
# scale with risk. Every referenced item/unlock is in the catalogs.
# --------------------------------------------------------------------------- #
_RISK_TIERS = {
    "baseline": dict(xp=100.0, item="eq_marksman", adds_unlock=False, bmin=50.0, bmax=200.0),
    "high": dict(xp=180.0, item="eq_rifle_hv", adds_unlock=True, bmin=120.0, bmax=360.0),
}


def _table_id(archetype, risk):
    return "rwt_{}_{}".format(archetype, risk)


def build_reward_tables():
    """Deterministic reward tables: 6 archetypes × 2 risk bands = 12 tables."""
    tables = []
    biomes = RX.KNOWN_BIOMES
    for ai, archetype in enumerate(RX.MISSION_ARCHETYPES):
        biome = biomes[ai % len(biomes)]
        cp_id = COMBAT_PROFILE_IDS[ai % len(COMBAT_PROFILE_IDS)]
        for risk, tier in _RISK_TIERS.items():
            entries = [
                {"reward_entry_id": "re_{}_{}_xp".format(archetype, risk), "reward_type": "xp",
                 "item_id": None, "xp_amount": tier["xp"], "unlock_id": None, "currency_amount": 0.0,
                 "weight": 2.0, "min_mission_result": "completed", "max_repeat_count": 5, "grant_once": False},
                {"reward_entry_id": "re_{}_{}_item".format(archetype, risk), "reward_type": "item",
                 "item_id": tier["item"], "xp_amount": 0.0, "unlock_id": None, "currency_amount": 0.0,
                 "weight": 1.0, "min_mission_result": "completed", "max_repeat_count": 1, "grant_once": True},
            ]
            if tier["adds_unlock"]:
                # Distinct unlock per mission archetype (1:1), so no unlock is ever
                # re-granted across the authoring chain.
                unlock_id = UNLOCK_IDS[ai % len(UNLOCK_IDS)]
                entries.append(
                    {"reward_entry_id": "re_{}_{}_unlock".format(archetype, risk), "reward_type": "unlock",
                     "item_id": None, "xp_amount": 0.0, "unlock_id": unlock_id, "currency_amount": 0.0,
                     "weight": 1.0, "min_mission_result": "completed", "max_repeat_count": 1, "grant_once": True})
            table = {
                "reward_table_id": _table_id(archetype, risk), "pack_id": PACK,
                "mission_archetype": archetype, "biome": biome, "combat_profile_id": cp_id,
                "risk_band": risk, "reward_entries": entries, "budget_min": tier["bmin"],
                "budget_max": tier["bmax"],
                "anti_exploit_rules": ["grant_once_stable", "budget_capped", "min_result_completed"],
                "seed": ai, "created_by": CREATED_BY, "created_at": CREATED_AT_AUTHORING,
                "schema_version": RX.REWARD_TABLE_SCHEMA_VERSION, "report_type": RX.RT_REWARD_TABLE,
            }
            tables.append(table)
    return tables


# --------------------------------------------------------------------------- #
# Grant simulation + state derivation (authoring model, shared with runtime).
# --------------------------------------------------------------------------- #
def _entry_value(entry):
    """Bounded scalar 'value' of a reward entry, for budget/classification."""
    v = 0.0
    if entry.get("reward_type") == "xp":
        v += float(entry.get("xp_amount") or 0.0)
    if entry.get("reward_type") == "item" and entry.get("item_id"):
        spec = {s[0]: s for s in _EQUIPMENT_SPEC}.get(entry["item_id"])
        v += float(spec[5]) * 3.0 if spec else 30.0  # power weighted
    if entry.get("reward_type") == "unlock" and entry.get("unlock_id"):
        v += 60.0
    if entry.get("reward_type") == "currency":
        v += float(entry.get("currency_amount") or 0.0)
    return v


def table_reward_value(table):
    """Total deterministic value a table grants on a completed mission."""
    return sum(_entry_value(e) for e in table.get("reward_entries", []))


def classify_risk_reward(risk_band, reward_value, budget_min, budget_max, duplicate_grant_once=False,
                         mission_completed=True):
    """Classify reward output against risk/budget. Returns (class, exploit_result).

    - no reward on an incomplete mission is not classified as reward here.
    - duplicate grant_once is always exploit_suspected.
    - value above budget_max = over_rewarded; below budget_min = under_rewarded.
    - within budget: high/extreme risk -> high_risk_high_reward, else baseline_reward.
    """
    if duplicate_grant_once:
        return "exploit_suspected", "suspected"
    if not mission_completed:
        return "invalid", "clean"
    if reward_value > budget_max:
        return "over_rewarded", "suspected"
    if reward_value < budget_min:
        return "under_rewarded", "clean"
    if risk_band in ("high", "extreme"):
        return "high_risk_high_reward", "clean"
    return "baseline_reward", "clean"


def simulate_grant(table, mission_id, scenario_id, source_completion_report,
                   source_combat_report=None, pre_inv=None, pre_prog=None):
    """Deterministically grant a table's rewards. Returns
    (grant_events, new_inventory, new_progression, unlock_states, classification).

    pre_inv / pre_prog are the prior InventoryState / ProgressionState (or None for
    a fresh player). State derivation mirrors what the runtime bridge must do.
    """
    inv = pre_inv or _empty_inventory(scenario_id)
    prog = pre_prog or _empty_progression(scenario_id)
    items = list(inv["items"])
    xp_gain = 0.0
    granted_items = []
    granted_unlocks = []
    events = []
    for idx, entry in enumerate(table["reward_entries"]):
        pre_inv_hash = _inv_hash(items)
        pre_prog_hash = _prog_hash(prog, xp_gain, granted_unlocks)
        rt = entry["reward_type"]
        gitem = None
        gunlock = None
        xp_amt = 0.0
        if rt == "xp":
            xp_amt = float(entry["xp_amount"])
            xp_gain += xp_amt
        elif rt == "item":
            gitem = entry["item_id"]
            items.append({
                "item_instance_id": "ii_{}_{}".format(scenario_id, entry["reward_entry_id"]),
                "item_id": gitem, "quantity": 1, "bound": True,
                "source_reward_event": "rge_{}_{}".format(scenario_id, idx), "acquired_at": "authoring"})
            granted_items.append(gitem)
        elif rt == "unlock":
            gunlock = entry["unlock_id"]
            granted_unlocks.append(gunlock)
        post_inv_hash = _inv_hash(items)
        post_prog_hash = _prog_hash(prog, xp_gain, granted_unlocks)
        events.append({
            "event_id": "rge_{}_{}".format(scenario_id, idx), "scenario_id": scenario_id,
            "mission_id": mission_id, "player_id": PLAYER_ID, "reward_table_id": table["reward_table_id"],
            "reward_entry_id": entry["reward_entry_id"], "reward_type": rt, "granted_item_id": gitem,
            "xp_amount": xp_amt, "unlock_id": gunlock, "pre_inventory_hash": pre_inv_hash,
            "post_inventory_hash": post_inv_hash, "pre_progression_hash": pre_prog_hash,
            "post_progression_hash": post_prog_hash, "timestamp": "authoring", "frame": 256 + idx,
            "source_completion_report": source_completion_report,
            "source_combat_report": source_combat_report,
            "schema_version": RX.REWARD_GRANT_EVENT_SCHEMA_VERSION, "report_type": RX.RT_REWARD_GRANT_EVENT,
        })

    new_inv = _build_inventory(scenario_id, items, inv["capacity"], inv["equipped_loadout_id"])
    new_prog = _apply_progression(prog, xp_gain, granted_unlocks, mission_id,
                                  table.get("mission_archetype"))
    unlock_states = [_build_unlock_state(uid, mission_id, "rge_{}_{}".format(scenario_id, i), scenario_id)
                     for i, uid in enumerate(granted_unlocks)]
    value = table_reward_value(table)
    cls, exploit = classify_risk_reward(table["risk_band"], value, table["budget_min"], table["budget_max"])
    classification = {"reward_table_id": table["reward_table_id"], "risk_band": table["risk_band"],
                      "reward_value": value, "budget_min": table["budget_min"],
                      "budget_max": table["budget_max"], "risk_reward_class": cls, "exploit_result": exploit}
    return events, new_inv, new_prog, unlock_states, classification


# ---- state helpers (mirror the contract hash functions) ----
def _inv_hash(items):
    return RX._inventory_hash(items)


def _prog_hash(prog, extra_xp, extra_unlocks=()):
    xp = float(prog["xp_total"]) + float(extra_xp)
    level = RX.level_for_xp(xp)
    unlocks = sorted(set(prog["unlocks"]) | set(extra_unlocks or ()))
    return RX._progression_hash(level, xp, unlocks, prog["completed_missions"])


def _empty_inventory(scenario_id):
    return _build_inventory(scenario_id, [], 32, "lo_scout_std")


def _build_inventory(scenario_id, items, capacity, loadout_id):
    inv = {
        "player_id": PLAYER_ID, "scenario_id": scenario_id, "inventory_id": "inv_{}".format(scenario_id),
        "items": items, "capacity": capacity, "equipped_loadout_id": loadout_id,
        "inventory_hash": RX._inventory_hash(items), "save_load_key": RX.INVENTORY_SAVE_SLOT,
        "schema_version": RX.INVENTORY_STATE_SCHEMA_VERSION, "report_type": RX.RT_INVENTORY_STATE,
    }
    return inv


def _empty_progression(scenario_id):
    return {
        "player_id": PLAYER_ID, "scenario_id": scenario_id, "level": 1, "xp_total": 0.0, "xp_delta": 0.0,
        "unlocks": [], "completed_missions": [], "completed_encounters": [],
        "progression_hash": RX._progression_hash(1, 0.0, [], []),
        "save_load_key": RX.PROGRESSION_SAVE_SLOT,
        "schema_version": RX.PROGRESSION_STATE_SCHEMA_VERSION, "report_type": RX.RT_PROGRESSION_STATE,
    }


def _apply_progression(prog, xp_gain, granted_unlocks, mission_id, encounter):
    xp_total = float(prog["xp_total"]) + float(xp_gain)
    level = RX.level_for_xp(xp_total)
    unlocks = sorted(set(prog["unlocks"]) | set(granted_unlocks))
    completed = sorted(set(prog["completed_missions"]) | {mission_id})
    completed_enc = sorted(set(prog["completed_encounters"]) | ({encounter} if encounter else set()))
    return {
        "player_id": PLAYER_ID, "scenario_id": prog["scenario_id"], "level": level, "xp_total": xp_total,
        "xp_delta": float(xp_gain), "unlocks": unlocks, "completed_missions": completed,
        "completed_encounters": completed_enc,
        "progression_hash": RX._progression_hash(level, xp_total, unlocks, completed),
        "save_load_key": RX.PROGRESSION_SAVE_SLOT,
        "schema_version": RX.PROGRESSION_STATE_SCHEMA_VERSION, "report_type": RX.RT_PROGRESSION_STATE,
    }


def _build_unlock_state(unlock_id, mission_id, source_event, scenario_id):
    utype = {u[0]: u[1] for u in _UNLOCK_SPEC}.get(unlock_id, "modifier")
    ag = {u[0]: u[2] for u in _UNLOCK_SPEC}.get(unlock_id, True)
    return {
        "unlock_id": unlock_id, "player_id": PLAYER_ID, "unlock_type": utype,
        "source_mission_id": mission_id, "source_reward_event": source_event,
        "available_from_scenario": "{}_next".format(scenario_id), "affects_generation": ag,
        "enabled": True, "schema_version": RX.UNLOCK_STATE_SCHEMA_VERSION,
        "report_type": RX.RT_UNLOCK_STATE,
    }


# --------------------------------------------------------------------------- #
# Save/load roundtrip — model-level persistence proof (no UE). Serializes a state
# to JSON and back, recomputes its content hash, and asserts stability. This is
# the authoring-side analogue of the runtime save/load proof; the runtime bridge
# proves the same invariant through a real UE SaveGame slot.
# --------------------------------------------------------------------------- #
def save_load_roundtrip(state, kind):
    """Return (ok, detail). kind in {'inventory','progression'}."""
    import json
    blob = json.dumps(state, sort_keys=True)
    reloaded = json.loads(blob)
    if kind == "inventory":
        recomputed = RX._inventory_hash(reloaded["items"])
        stored = reloaded.get("inventory_hash")
    else:
        recomputed = RX._progression_hash(reloaded["level"], reloaded["xp_total"],
                                          reloaded["unlocks"], reloaded["completed_missions"])
        stored = reloaded.get("progression_hash")
    ok = (recomputed == stored) and (reloaded == state)
    return ok, "roundtrip {} hash {}".format(kind, "stable" if ok else "DRIFTED")


def build_reward_telemetry(scenario_id, granted_unlocks, no_reward=False):
    """A contract-valid reward telemetry event stream for a scenario."""
    if no_reward:
        types = ["reward.scenario.started", "reward.mission.completion.read",
                 "reward.table.selected", "reward.scenario.no_reward", "reward.scenario.completed"]
    else:
        types = ["reward.scenario.started", "reward.mission.completion.read",
                 "reward.combat.completion.read", "reward.table.selected", "reward.grant.applied",
                 "reward.inventory.mutated", "reward.progression.mutated"]
        types += ["reward.unlock.granted"] if granted_unlocks else []
        types += ["reward.state.saved", "reward.state.reload.verified",
                  "reward.next_mission.state.written", "reward.risk_reward.classified",
                  "reward.scenario.completed"]
    return {"report_type": RX.RT_REWARD_TELEMETRY, "scenario_id": scenario_id,
            "events": [{"event_type": t, "frame": 200 + i} for i, t in enumerate(types)]}


def build_reward_completion(scenario, created_at="authoring", git_commit="unknown"):
    """Build a contract-valid RewardCompletionReport from a scenario evidence dict."""
    inv_mut = bool(scenario["grant_events"]) and any(
        e["reward_type"] in ("item",) for e in scenario["grant_events"])
    prog_mut = any(e["reward_type"] in ("xp", "unlock") for e in scenario["grant_events"])
    items = sorted({e["granted_item_id"] for e in scenario["grant_events"] if e.get("granted_item_id")})
    unlocks = sorted({e["unlock_id"] for e in scenario["grant_events"] if e.get("unlock_id")})
    xp = sum(float(e.get("xp_amount") or 0.0) for e in scenario["grant_events"])
    cls = scenario["classification"]["risk_reward_class"]
    exploit = scenario["classification"]["exploit_result"]
    return {
        "report_id": "reward_cmp:{}".format(scenario["scenario_id"]),
        "scenario_id": scenario["scenario_id"], "map_id": scenario["map_id"],
        "mission_id": scenario["mission_id"], "encounter_id": scenario["encounter_id"],
        "biome": scenario["biome"], "combat_profile_id": scenario["combat_profile_id"],
        "mission_completed": True, "combat_completed": True,
        "reward_table_id": scenario["reward_table_id"],
        "reward_events_seen": len(scenario["grant_events"]), "items_granted": items,
        "xp_granted": xp, "unlocks_granted": unlocks, "inventory_mutated": inv_mut,
        "progression_mutated": prog_mut, "next_mission_state_written": True,
        "save_load_result": "pass", "risk_reward_class": cls, "exploit_result": exploit,
        "status": "pass", "completion_class": "reward_granted_runtime",
        "telemetry_path": "{}/reward_telemetry_{}.json".format(
            RX.REWARD_TELEMETRY_REPORTS_REL, scenario["scenario_id"]),
        "evidence_paths": ["{}/reward_telemetry_{}.json".format(
            RX.REWARD_TELEMETRY_REPORTS_REL, scenario["scenario_id"])],
        "failure_owner": None, "failure_codes": [], "created_at": created_at,
        "git_commit": git_commit, "source_combat_report": scenario.get("source_combat_report"),
        "schema_version": RX.REWARD_COMPLETION_SCHEMA_VERSION, "report_type": RX.RT_REWARD_COMPLETION,
    }


def build_authoring_scenarios():
    """The chained authoring evidence set: one scenario per reward table, applied
    in order to a SINGLE accumulating player so progression/unlocks build up and
    scenario_i's pre-state is scenario_{i-1}'s post-state. This is what gives the
    next-mission handoff a real state chain to prove. Returns a list of scenario
    evidence dicts (each fully contract-valid). Deterministic — no wall-clock/RNG.
    """
    tables = build_reward_tables()
    scenarios = []
    inv = None
    prog = None
    prev_scenario_id = None
    prev_prog_hash = None
    for i, table in enumerate(tables):
        archetype = table["mission_archetype"]
        scenario_id = "rs_auth_{:02d}_{}".format(i, table["reward_table_id"])
        mission_id = "m_auth_{}".format(archetype)
        map_id = "MAP_auth_{:02d}".format(i)
        encounter_id = "enc_{}_{}".format(map_id, archetype)
        completion_path = "{}/reward_completion_{}.json".format(
            RX.REWARD_COMPLETION_REPORTS_REL, scenario_id)
        combat_path = "procedural/reports/combat/completion/cs_{}.json".format(map_id)
        events, inv, prog, unlock_states, classification = simulate_grant(
            table, mission_id, scenario_id, completion_path, combat_path, pre_inv=inv, pre_prog=prog)
        # Re-key the accumulating inventory/progression scenario id to this scenario.
        inv["scenario_id"] = scenario_id
        inv["inventory_id"] = "inv_{}".format(scenario_id)
        prog["scenario_id"] = scenario_id
        granted_unlocks = [u["unlock_id"] for u in unlock_states]
        scenario = {
            "scenario_id": scenario_id, "mission_id": mission_id, "map_id": map_id,
            "encounter_id": encounter_id, "biome": table["biome"],
            "mission_archetype": archetype, "combat_profile_id": table["combat_profile_id"],
            "risk_band": table["risk_band"], "reward_table_id": table["reward_table_id"],
            "grant_events": events, "inventory_state": inv, "progression_state": prog,
            "unlock_states": unlock_states, "classification": classification,
            "source_combat_report": combat_path,
            "prev_scenario_id": prev_scenario_id, "prev_progression_hash": prev_prog_hash,
        }
        scenario["reward_telemetry"] = build_reward_telemetry(scenario_id, granted_unlocks)
        scenario["reward_completion"] = build_reward_completion(scenario)
        scenarios.append(scenario)
        prev_scenario_id = scenario_id
        prev_prog_hash = prog["progression_hash"]
    return scenarios


def meta(command, status, record_count, report_type):
    return build_meta(command=command, pack=PACK, strict=True, status=status,
                      record_count=record_count, report_type=report_type,
                      records_total=record_count)
